### ISSUE TITLE
What is the minimum java version? (6, 7)

### ISSUE THREAD

**Issue by Try4W** [nhaarman/mockito-kotlin#103]
There were no methods like `mock(...)` in autocompletion until I changed sourceCompatibility from 1.6 to 1.7
Then I change it back to 1.6 and everything still works.

Before it I tried to restart idea&clean cache etc.

**Comment by nhaarman** [comment]
The library is just compiled with Kotlin, so it is compatible with Java 6 or newer. 
See https://kotlinlang.org/docs/reference/faq.html#which-minimum-java-version-is-required-for-running-kotlin-code.
