### ISSUE TITLE
Enable mocking of final (non-open) classes and methods by default

### ISSUE THREAD

**Issue by angryziber** [nhaarman/mockito-kotlin#114]
Mockito 2.2 now supports it as an opt-in feature.

I think mockito-kotlin should enable it by providing the `mockito-extensions/org.mockito.plugins.MockMaker` file with `mock-maker-inline` content.

https://github.com/mockito/mockito/wiki/What's-new-in-Mockito-2#unmockable

There is even a FAQ question about that here :-)

**Comment by nhaarman** [comment]
See #86.
Not enabling this since the feature is incubating and opt-in in Mockito itself. Once it's stable enough and no real issues arise from it, we might include this too. May it be that Mockito handles this for us though.

I will update the wiki.
