### ISSUE TITLE
any() causes NullPointerException for Strings

### ISSUE THREAD

**Issue by Shyish** [nhaarman/mockito-kotlin#124]
Taking this example:

```
interface Api {
  fun search(query: String):Observable<...>
}
```
```
whenever(api.search(any()).thenReturn(empty())
```

It crashes with `java.lang.IllegalArgumentException: Parameter specified as non-null is null` for latest version of both this `0.12.1` and mockito `2.2.21`

**Comment by nhaarman** [comment]
Can you provide the stacktrace?
What version of Kotlin are you using, and which Java version?

**Comment by nhaarman** [comment]
@Shyish could you create a reproducible example with the extra information above please?

**Comment by Shyish** [comment]
Hello Niek,

I'm sorry I didn't had time yet. I'll do that this week ASAP!

Cheers

On Sun, Nov 27, 2016, 17:19 Niek Haarman <notifications@github.com> wrote:

@Shyish <https://github.com/Shyish> could you create a reproducible example
with the extra information above please?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/nhaarman/mockito-kotlin/issues/124#issuecomment-263131054>,
or mute the thread

**Comment by nhaarman** [comment]
:+1: no worries

**Comment by Shyish** [comment]
Cannot reproduce, might have happened due to a wrong build or something, sorry for the worries.

**Comment by nhaarman** [comment]
Ah, no problem. Thanks!
