### ISSUE TITLE
Mocked methods that return nullable collections return non-null value by default

### ISSUE THREAD

**Issue by ovsyankin** [nhaarman/mockito-kotlin#128]
Given there is an interface

```kotlin
interface Service {
    fun getStrings(): Collection<String>?
    fun getStuff(): Stuff
}

data class Stuff(val a: String)
```

and a test that mocks the interface and calls and checks its methods sequentially

```kotlin
class MockitoKotlinTest {
    @Test fun `check mocking`() {
        val client = mock<Service>()

        assertThat(client.getStuff()).isNull()
        assertThat(client.getStrings()).isNull() // <-- fails here
    }
}
```

the ```assertThat(client.getStrings()).isNull()``` assertion will fail because by default mockito-kotlin makes it return LinkedList rather than null, despite the fact that interface explicitly allows null as return value. If I do something like

```
        whenever(client.getStrings()).thenReturn(null)
```

then test passes as expected, but it would be great if default return value for nullable collections were nulls.

Affected versions: 0.10.0, 0.10.1, 0.12.2

**Comment by nhaarman** [comment]
This is expected behavior as per Mockito itself:

> By default, for all methods that return a value, a mock will return either null, a a primitive/primitive wrapper value, or **an empty collection**, as appropriate. For example 0 for an int/Integer and false for a boolean/Boolean.

See http://static.javadoc.io/org.mockito/mockito-core/2.2.27/org/mockito/Mockito.html#2.

Since there is no intention to change any semantic behavior that Mockito provides, this library will not change this.
