### ISSUE TITLE
Missing pom for v0.2.1

### ISSUE THREAD

**Issue by jayrave** [nhaarman/mockito-kotlin#13]
Hey Haarman, the latest version on [bintray] (https://bintray.com/nhaarman/maven/Mockito-Kotlin/0.2.1/view#files/com/nhaarman/mockito-kotlin/0.2.1) (0.2.1 as of 02/19/2016) doesn't have any pom files associated with it!! So gradle fails to pull in kotlin-reflect automatically

Also sources and javadoc jars are missing

Can you please fix this?

Thanks for a great library

**Comment by nhaarman** [comment]
Ah, you're right.
I have reuploaded the files.
