### ISSUE TITLE
Easy way to make a mock with settings

### ISSUE THREAD

**Issue by wafisher** [nhaarman/mockito-kotlin#148]
Is there an easy way to include `MockSettings` (in particular, `RETURNS_DEEP_STUBS`) using this syntax? It seems like you can either use [this](https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/Mockito.kt#L125) or [this](https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/Mockito.kt#L128) but not both.

Thanks!

**Comment by nhaarman** [comment]
Can you give an example of how you would use it in Java?

**Comment by wafisher** [comment]
Sure, here it is in Kotlin. Mostly it's that `RETURNS_DEEP_STUBS` bit that I can't easily put in now.

```
val trip = Mockito.mock(Trip::class.java, RETURNS_DEEP_STUBS)
Mockito.`when`(trip.someFn().nestedFn()).thenReturn(returnMe)
```

**Comment by nhaarman** [comment]
Ah, so if I understand correctly you'd want some syntax like the following?

```
val trip = mock<Trip>(RETURNS_DEEP_STUBS) {
  on { someFn().nestedFn() } doReturn returnMe
}

**Comment by wafisher** [comment]
Exactly. Is that reasonable?

**Comment by nhaarman** [comment]
Sounds valid. Perhaps something can be done with a parameter with a default value. I'll have a look later on!

**Comment by nhaarman** [comment]
The `MockSettings` object is essentially a Builder. With that in mind, we can create the following function to replace the current `withSettings()`:

```kotlin
fun withSettings(
      extraInterfaces: Array<KClass<Any>>? = null,
      name: String? = null,
      spiedInstance: Any? = null,
      defaultAnswer: Answer<Any>? = null,
      serializable: Boolean = false,
      serializableMode: SerializableMode? = null,
      verboseLogging: Boolean = false,
      invocationListeners: Array<InvocationListener>? = null,
      stubOnly: Boolean = false,
      @Incubating useConstructor: Boolean = false,
      @Incubating outerInstance: Any? = null
): MockSettings
```

This will not break current code as they will all use the default values. 
Using this, we can do the following:

```diff
-inline fun <reified T : Any> mock(): T
+inline fun <reified T : Any> mock(
+      extraInterfaces: Array<KClass<Any>>? = null,
+      name: String? = null,
+      spiedInstance: Any? = null,
+      defaultAnswer: Answer<Any>? = null,
+      serializable: Boolean = false,
+      serializableMode: SerializableMode? = null,
+      verboseLogging: Boolean = false,
+      invocationListeners: Array<InvocationListener>? = null,
+      stubOnly: Boolean = false,
+      @Incubating useConstructor: Boolean = false,
+      @Incubating outerInstance: Any? = null
+): T 
```

Usage would be intuitive:

```kotlin
val myMock = mock<MyClass>(
  name = "Custom name",
  verboseLogging = true
)
```

The same can be done for the stubbing variant:

```kotlin
val myMock = mock<MyClass>(
  name = "Custom name",
  verboseLogging = true
) {
  on { doSomething() } doReturn true
}
```

If this is introduced, we can deprecate the other `mock` functions (`mock(Answer)`, `mock(MockSettings)` and `mock(String)`).

What do you think?

**Comment by wafisher** [comment]
That looks awesome. Thanks for the quick turnaround!

**Comment by nhaarman** [comment]
Great! I'll do some field tests tomorrow and draft a release in the coming week probably.
