### ISSUE TITLE
Support for Answers in mock setup

### ISSUE THREAD

**Issue by sazzer** [nhaarman/mockito-kotlin#151]
It would be very useful to be able to do a `doAnswer` in the same way as a `doReturn` or a `doThrow`. Something like:
```
private val userDao: UserDao = mock {
    on(this.save(any())) doAnswer { user ->
        UserModel(id = "userId", version = 1L, userData = user)
    }
}
```

At the moment I'm having to do this in an @Before or else in each test case.

**Comment by nhaarman** [comment]
Note that you can still use `whenever(mock.method()).doAnswer()` using the current version of Mockito-Kotlin.

**Comment by sazzer** [comment]
Sorry - I meant that this is what I'm doing in my @Before method, exactly as you describe. It's just that having it as a doAnswer would mean I don't need the @Before at all...

**Comment by nhaarman** [comment]
Oh, now I see you're initializing the variable directly :+1: My bad.

**Comment by sazzer** [comment]
Yeah - I'm using JUnit so I often do all the mocks and test subject directly as class fields. Works well for me, and JUnit guarantees that they are clean for each test.

**Comment by nhaarman** [comment]
> JUnit guarantees that they are clean for each test.

It doesn't do that out of the box, does it?

**Comment by sazzer** [comment]
JUnit creates a new instance of the class under test for each test method,
so all class fields are freshly initiated for each test. Conversely, TestNG
creates the class once and reuses it for every test method.

**Comment by nhaarman** [comment]
Hmm, might be misunderstanding, but in the example below, `instance` is only assigned once for both tests, right?

```java
class MyTest {

   MyClass instance = new MyClass();

   @Test
   public void testSomething() {
      ...
   }

   @Test
   public void testSomethingElse() {
      ...
   }
}
```

**Comment by sazzer** [comment]
I'm that example, `MyTest` will be instantiated twice - once for `testSomething()` and again for `testSomethingElse()`. I'm both cases, because `MyTest` is a new instance, `instance` will be assigned a new instance of `MyClass`.

**Comment by nhaarman** [comment]
Oh wow, that's something new to me. My understanding was that `TestClass` would only be created once for all the tests. TIL ;)

Thanks for that!

**Comment by sazzer** [comment]
That's exactly how TestNG works, and JUnit can be configured to work that way, but by default it does a new instance per test method. It's a way to help ensure that the tests are independent of each other - barring anything external...

**Comment by nhaarman** [comment]
By the way -- when you say the following:

```kotlin
on(this.save(any())) doAnswer { user ->
     UserModel(id = "userId", version = 1L, userData = user)
}
```

The `user` variable is not actually a `User` instance, but rather an `InvocationOnMock` instance, from which you can extract the arguments. So it would look more like

```kotlin
on(this.save(any())) doAnswer { invocation ->
     val user = invocation.arguments[0] as User
     UserModel(id = "userId", version = 1L, userData = user)
}
```

**Comment by sazzer** [comment]
Hmm, yes you're right. And you've helped me find a hole in my tests... :-)

**Comment by nhaarman** [comment]
See #152. That should work for you?

**Comment by sazzer** [comment]
Wow - yes, that looks great. You don't hang around :-)

**Comment by nhaarman** [comment]
You helped me, I'm helping you ;)

1.3.0 should be available on JCenter and Maven Central soon!
