### ISSUE TITLE
Breaks on Kotlin 1.1 beta

### ISSUE THREAD

**Issue by atfox7** [nhaarman/mockito-kotlin#155]
If I have Kotlin set to version 1.1.0-beta-38 I get the following error.

> e: Some runtime JAR files in the classpath have an incompatible version. Remove them from the classpath or pass the correct '-language-version' explicitly. Alternatively, you can use '-Xskip-runtime-version-check' to suppress this error
> .....gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.6/3d499d3b7768f88c4796e5a1e357933e11a8936d/kotlin-reflect-1.0.6.jar: Runtime JAR file has version 1.0 which is older than required for language version 1.1

Setting Kotlin back to 1.0.6 solves the problem. Would be nice to get a release of this updated for kotlin-reflect-1.1.

**Comment by nhaarman** [comment]
I'm waiting for the 1.1.0 release before releasing any Mockito-Kotlin versions that depend on non-final versions of Kotlin.

Instead, you can use the following to overcome the issue, in your root's `build.gradle`:

```groovy
allprojects {
    configurations.all {
        resolutionStrategy {
            forcedModules = ["org.jetbrains.kotlin:kotlin-stdlib:1.1.0-beta-38", "org.jetbrains.kotlin:kotlin-reflect:1.1.0-beta-38"]
        }
    }
}

**Comment by atfox7** [comment]
Ah good point. Thanks for the workaround tip!
