### ISSUE TITLE
'Whenever' works only with lambda

### ISSUE THREAD

**Issue by fatalDefloration** [nhaarman/mockito-kotlin#161]
Hello @nhaarman ,

I got a problem using 'whenever' method in my test. And here is what I found:
- this way it works exactly as expected:
`val locationManager = mock<GeolocationManager> { on { isUserInZone(userLocation, placeLocation) } doReturn false }`

- this way I got and assertion:
`private val locationManager: GeolocationManager = mock()`
`whenever(locationManager.isUserInZone(userLocation, placeLocation)).doReturn(false)
`

Please correct me if I use it in inappropriate way.

Best regards,
Yakov

Here is a stacktrace:

> Wanted but not invoked:
> view.onUserIsOutOfZone();
> -> at com.wate.watevisitor.ui.place_details.PlaceDetailsPresenterTest.link_up_user_out_of_zone(PlaceDetailsPresenterTest.kt:150)
> at com.wate.watevisitor.ui.place_details.PlaceDetailsPresenterTest.link_up_user_out_of_zone(PlaceDetailsPresenterTest.kt:150)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

By the way, here is dependencies:
```
testCompile 'junit:junit:4.12'
    testCompile "com.nhaarman:mockito-kotlin:1.3.0"
    testCompile "org.mockito:mockito-inline:2.7.17"
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:1.1.1"
```

**Comment by fatalDefloration** [comment]
I think I understand what was the the point. 

Stubbing worked this way:
```
whenever(locationManager.isUserInZone(userLocation, placeLocation)).doReturn(true)
verify(locationManager).getLastKnownLocation(locationCallback.capture())
locationCallback.firstValue.onReceivedSuccessfully(userLocation)
verify(locationManager).isUserInZone(userLocation, placeLocation)
```

But not this way:
```
verify(locationManager).getLastKnownLocation(locationCallback.capture())
locationCallback.firstValue.onReceivedSuccessfully(userLocation)
whenever(locationManager.isUserInZone(userLocation, placeLocation)).doReturn(true)
verify(locationManager).isUserInZone(userLocation, placeLocation)
```

And not this way:
```
verify(locationManager).getLastKnownLocation(locationCallback.capture())
locationCallback.firstValue.onReceivedSuccessfully(userLocation)
whenever(locationManager.isUserInZone(userLocation, placeLocation)).doReturn(true)
```

Is that correct behaviour?

**Comment by nhaarman** [comment]
I'm not sure what's going on here. Could you perhaps create a [Short, Self Contained, Correct Example](http://sscce.org/)?
