### ISSUE TITLE
Kotlin 1.1 Migration

### ISSUE THREAD

**Issue by kiwiandroiddev** [nhaarman/mockito-kotlin#162]
Just wondering if bumping to Kotlin 1.1 is something in the pipeline?

Thanks for your work on this library - we're making heavy use of it on an Android project.

Edit: just saw this commit: https://github.com/nhaarman/mockito-kotlin/commit/a52ae865d89ab50f804fc4938f44bdcaeb4e5754
Disregard :)

**Comment by nhaarman** [comment]
The library is built with Kotlin 1.0.x, but works with 1.1.x just fine. The main reason for not bumping the library's dependency to 1.1.x is to make sure no 1.1.x features are used that will break users who are still on 1.0.x.

If you get an error which mentions a conflict between 1.0.x and 1.1.0, see [this page](https://github.com/nhaarman/mockito-kotlin/wiki/FAQ#dependencyconflict).
