### ISSUE TITLE
After adding this to my Android project, normal JUnit tests fail

### ISSUE THREAD

**Issue by autonomousapps** [nhaarman/mockito-kotlin#164]
Using version 1.4.0.

I get this error:

```
java.lang.AbstractMethodError: org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.isTypeMockable(Ljava/lang/Class;)Lorg/mockito/plugins/MockMaker$TypeMockability;
```

This test passed prior to adding mockito-kotlin. It complains on this line:

```java
Thing thing = Mockito.mock(Thing.class); // Thing is a public INTERFACE defined in Java
```

If I remove that, the test still fails, but at a different line. I think it's here:

```java
@Mock Thing2 thing2; // Thing2 is a public non-final CLASS defined in Java
```

Other dependencies in `build.gradle`:

```groovy
    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-library:1.3'
    testCompile 'org.mockito:mockito-core:2.0.5-beta'
    testCompile("org.powermock:powermock-api-mockito:$powermock_version") { // 1.6.2
        exclude module: 'hamcrest-core'
        exclude module: 'objenesis'
    }
    testCompile("org.powermock:powermock-module-junit4:$powermock_version") {
        exclude module: 'hamcrest-core'
        exclude module: 'objenesis'
    }
```

**Comment by nhaarman** [comment]
Mockito-kotlin depends on a newer, non-beta version of Mockito. You were using 2.0.5-beta, which is now bumped to 2.7.21. You might want to try and update your mockito version and get that working first before including mockito-kotlin.

**Comment by autonomousapps** [comment]
I appear to be caught in dependency hell. Our project also uses PowerMock, which has a hardcoded dependency on an old version of Mockito. From my investigation so far, this won't really be fixed until PowerMock 2 is released, and no clue when that will be.

I'll hack away at it a bit more (with an axe), and update this issue if I find a solution. Thanks for the hint about Mockito 2.7.21.

**Comment by nhaarman** [comment]
Let me close this for now. The main issue seems to be with the PowerMock usage.

**Comment by starkej2** [comment]
I'm encountering a similar error. Did you figure out a solution @autonomousapps? The tests seem to work fine if PowerMock is disabled...

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
Caused by: java.lang.NoClassDefFoundError: org/mockito/cglib/proxy/MethodInterceptor
```

**Comment by autonomousapps** [comment]
@starkej2 thanks for asking; I had meant to return and discuss my findings. Basically, I just removed PowerMock from the project. It has a strict dependency on a beta version of Mockito2, and it did not seem as if it would be updating that in the near future. Fortunately, after some refactorings it was no longer necessary for us to use PowerMock -- normal Mockito was fine.

A caveat: if/when you update Mockito to the latest, and assuming you also use Hamcrest, you'll find a few breaking changes from the Mockito beta. They're relatively easy to fix, however.

**Comment by autonomousapps** [comment]
If it helps, here are our current relevant test dependencies:

```
    testCompile 'junit:junit:4.12'
    testCompile "org.mockito:mockito-core:$mockito_version" // 2.8.9
    testCompile "org.hamcrest:hamcrest-library:$hamcrest_version" // 1.3
    testCompile 'cglib:cglib-nodep:2.2.2'
    testCompile 'org.objenesis:objenesis:1.2'

    // Kotlin testing
    testCompile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version" // 1.1.2-3
    testCompile "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testCompile 'com.nhaarman:mockito-kotlin:1.4.0'
    testCompile 'org.amshove.kluent:kluent:1.14'
```

**Comment by starkej2** [comment]
Thanks @autonomousapps! We ended up refactoring out the need for PowerMock too...seemed like the easiest fix
