### ISSUE TITLE
The argumentCaptor aways return null when the capture() functions is called

### ISSUE THREAD

**Issue by jackmiras** [nhaarman/mockito-kotlin#166]
I'm trying to run a `argumentCaptor` but every time that try to run the block down bellow the `capture()` function return null in every call.

```kotlin
it("should have a positive match as a non empty id filter") {
    val baseRepository = mock<BaseRepository>()
    argumentCaptor<String>().apply {
        verify(baseRepository).findBy("_id", capture(), User::class)
        user.id shouldEqualTo lastValue
    }
}
```
Does you guys know how to solve or work around this?

**Comment by nhaarman** [comment]
Do you have a stack trace?

**Comment by jackmiras** [comment]
Hi @nhaarman I would like to apologize for open this issue, for some reason that I don't know the code start working. I'm guessing that something else in my code base was broken start to cause side effects in other test classes.

**Comment by nhaarman** [comment]
Ok, no problem! Thanks for the update.

**Comment by uchiharizvi** [comment]
What was the solution? I am facing similar issue
