### ISSUE TITLE
Mockito-kotlin not using the latest version for the kotlin plugin

### ISSUE THREAD

**Issue by w3b5urf3r** [nhaarman/mockito-kotlin#168]
When I build my app I have this issue
Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-stdlib' in project ':app'. Resolved versions for app (1.1.2-3) and test app (1.0.4) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
as reported the version of Kotlin differs so that the behaviour in the tests and in the app can be different. 

Mockito kotlin needs to be build with the latest version for kotlin

**Comment by w3b5urf3r** [comment]
Just Spotted the FAQ answer

**Comment by fred01** [comment]
Sorry, but second method you mentioned in FAQ doesn't work for me. Kotlin still show this warning. Do you planning to upgrade kotlin-reflect version in dependencies?

**Comment by w3b5urf3r** [comment]
@fred01 it worked for me can I see your code?

**Comment by fred01** [comment]
Hi! Thank you for answer!
this is part of my depedencies section of build.gradle

    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile "com.nhaarman:mockito-kotlin:1.4.0"
    testCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

$kotlin_version declared as

    buildscript {
        ext.kotlin_version = '1.1.2-2'

And i still see this warning on compile time

**Comment by fred01** [comment]
Sorry, my bad. 1.0.3 dependency actually was pulled by jackson-kotlin-module from one of submodule
