### ISSUE TITLE
any() returns null for MutableLists

### ISSUE THREAD

**Issue by alilotfi** [nhaarman/mockito-kotlin#169]
Hi
First thanks for your awesome library which made Kotlin and Mockito such good friends

It seems that `any()` will return `null` in place of any `MutableList<T>`
The following piece of code contains everything needed to reproduce this issue:

    interface Manager {
        fun delete(users: MutableList<Int>): Boolean
    }
    
    open class ManagerImpl : Manager {
        override fun delete(users: MutableList<Int>): Boolean {
            return true
        }
    }
    
    class Test {
        @Test
        fun `Stubbing a spy`() {
            val manager: Manager = spy(ManagerImpl() as Manager)
            whenever(manager.delete(any())) `it returns` true
        }
    }

Running this test will lead to the following excetpion:

    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method ir.miare.courier.ManagerImpl.delete, parameter users
    
    at ir.miare.courier.ManagerImpl.delete(Test.kt)
    at ir.miare.courier.Test.Stubbing a spy(Test.kt:25) <27 internal calls>

*I can provide full stack trace if it helps.*

Thank you.

**Comment by alilotfi** [comment]
And also about version:

    com.nhaarman:mockito-kotlin:1.4.0
    ext.kotlin_version = '1.1.2-3'

and this `resolutionStrategy`

    forcedModules = [
        "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version",
        "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    ]

**Comment by nhaarman** [comment]
This is ultimately the problem with spies, as the spied method is still run and a null-check throws an NPE when the method is called with `any()`. For really mocked methods, this isn't the case.

[`any()` always returns `null`](https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/createinstance/NullCaster.kt), so this problem will exist for for example `String` parameters as well.

If you can avoid using `spy`, I'd try that, as that is more idiomatic as well.

**Comment by alilotfi** [comment]
Thanks for the response.
BTW, I'm not aware of mockito internals about spied methods but I thought null-check will not performed in case of using `when()` phrases.

**Comment by bountin** [comment]
If you come from Google looking for a solution, here it is: https://github.com/nhaarman/mockito-kotlin/issues/241#issuecomment-399087031
