### ISSUE TITLE
Wiki could be clearer on matcher usage

### ISSUE THREAD

**Issue by erikthered** [nhaarman/mockito-kotlin#170]
From looking at the wiki, it isn't immediately clear that mockito-kotlin introduces its own matcher functions (eq(), any(), etc.) that should be used instead of Mockito's functions.

**Comment by nhaarman** [comment]
Thanks! I have [included this ](https://github.com/nhaarman/mockito-kotlin/wiki/Mocking-and-verifying/_compare/19144098d606cd70db1bea70f3cc410cf48f358d...4b948ae98bfda46921b6b43f8692d991a9716fb1)in the Wiki.
