### ISSUE TITLE
Assertion failing in the argumentCaptor() function

### ISSUE THREAD

**Issue by jackmiras** [nhaarman/mockito-kotlin#172]
When I try to check if a capture argument has the same type of an class or is equal to another object I'm getting the following error:
```Gradle
Failures (1):
  Spek:UserRepositoryTest:given the user repository
      :given a call to the save function
      :on the attempt of save an user
      :it should entity be an user
    => java.lang.AssertionError: expected:<user.User@93d5b66e> but was:<java.lang.Object@4795ded0>
```
The test that I'm trying to run is written as the example down below:
```Kotlin
given("a call to the save function") {
    afterGroup { userFactory.clear() }

    on("the attempt of save an user") {

        it("should entity be an user") {
            val user = userFactory.create()
            userRepositoryMocked.save(user)
            argumentCaptor<User>().apply {
                verify(userRepositoryMocked, atLeastOnce()).save(capture())
                firstValue shouldEqual user
            }
        }

    }

}
```
In the example above I'm using [Kluent](https://markusamshove.github.io/Kluent/) library to perform the assertions but I've also tried to perform the same assertion with `Asser.assertEqual()` from **JUnit** but nothing change.

**Comment by nhaarman** [comment]
This is not the place for debugging questions like this. The most likely thing is that `userRepositoryMocked.save()` is being called elsewhere.
