### ISSUE TITLE
How can I mock setter for a property?

### ISSUE THREAD

**Issue by nbarishok** [nhaarman/mockito-kotlin#173]
syntax like `whenever(instance.property).doReturn(TEST_RESULT)` works for getters only

**Comment by nbarishok** [comment]
Ok, seems I got it. Leave the answer, just in case
```
doAnswer {
        // invocation on any interaction with setter
        }.whenever(instance).property = any()
```

**Comment by nhaarman** [comment]
This is explained just fine in the [wiki](https://github.com/nhaarman/mockito-kotlin/wiki/Mocking-and-verifying#properties).

**Comment by nhaarman** [comment]
This is explained just fine in the [wiki](https://github.com/nhaarman/mockito-kotlin/wiki/Mocking-and-verifying#properties).

**Comment by polson** [comment]
That doesn't answer the question at all

**Comment by crazyguysdev** [comment]
> Ok, seems I got it. Leave the answer, just in case
> 
> ```
> doAnswer {
>         // invocation on any interaction with setter
>         }.whenever(instance).property = any()
> ```

I didn't get your solution at the first time, so I add example for those who like me
``` kotlin
// Mock android View
val view = mock<View>()

// Stub `setVisibility` of `View` for `any()` parameter is given for parameter
doNothing().whenever(view).visibility = any()

// The stubbed `doNothing()` executed for statement below
view.visibility = View.GONE
```
