### ISSUE TITLE
Avoid using underscore in sub-package name in next major version

### ISSUE THREAD

**Issue by sdeleuze** [nhaarman/mockito-kotlin#180]
Usage of package with underscore in sub-package name seems pretty non-standard in Java and Kotlin, it would be awesome if in a future (major) version your could avoid using it.

Changing `com.nhaarman.mockito_kotlin` to, for example, `com.nhaarman.mockito.kotlin` would make my eyes stop bleeding ;-)

**Comment by nhaarman** [comment]
Version `2.x` proposes to use `com.nhaarman.mockitokotlin2`: https://github.com/nhaarman/mockito-kotlin/releases/tag/2.0.0-alpha01

**Comment by sdeleuze** [comment]
@nhaarman Thanks! Any chance to avoiding the version in the package and just use `com.nhaarman.mockitokotlin`?

**Comment by nhaarman** [comment]
The `2` is there to be constistent with this interoperability policy between major versions: http://jakewharton.com/java-interoperability-policy-for-major-version-updates/
