### ISSUE TITLE
mockito-kotlin-kt1.1 not using latest version of Kotlin plugin (1.1.3)

### ISSUE THREAD

**Issue by andersu** [nhaarman/mockito-kotlin#181]
Error:Conflict with dependency 'org.jetbrains.kotlin:kotlin-stdlib' in project ':app'. Resolved versions for app (1.1.3) and test app (1.1.2-4) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

**Comment by leandroBorgesFerreira** [comment]
Same here =/

**Comment by thuytrinh** [comment]
You can do like this & move on:

```groovy
testCompile 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0', { exclude group: 'org.jetbrains.kotlin' }
```

**Comment by bonoj** [comment]
Thank you, thuytrinh!

**Comment by leodeleon22** [comment]
That's my build.gradle I still have the problem 

```
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    
    testCompile 'org.jetbrains.spek:spek-api:1.1.2'
    testCompile 'org.jetbrains.spek:spek-junit-platform-engine:1.1.2'
    testCompile 'org.junit.platform:junit-platform-runner:1.0.0-RC1'
    testCompile 'org.mockito:mockito-core:2.5.0'
    testCompile 'com.nhaarman:mockito-kotlin-kt1.1:1.5.0', { exclude group: 'org.jetbrains.kotlin' }
```

**Comment by dibog** [comment]
I'm a maven user, it would be great if you could release a new version of this plugin when there is a new kotlin version.

**Comment by nhaarman** [comment]
@dibog Ideally the `mockito-kotlin-kt1.1` artifact is dropped as well. Doesn't manually including the `kotlin-reflect` library solve the problem in maven?

**Comment by nhaarman** [comment]
See https://github.com/nhaarman/mockito-kotlin/wiki/Conflict-with-dependency
