### ISSUE TITLE
Add shield to show the current version

### ISSUE THREAD

**Issue by ftomassetti** [nhaarman/mockito-kotlin#184]
Like we do in JavaParser

<img width="675" alt="screen shot 2017-07-04 at 11 23 46" src="https://user-images.githubusercontent.com/439078/27823993-49bd7bd8-60ab-11e7-9ad7-e258b4c85a1c.png">

**Comment by nhaarman** [comment]
It's there already?

![image](https://user-images.githubusercontent.com/3015152/27827436-907c07d6-60b7-11e7-8d06-2fcdc86b82e6.png)

**Comment by ftomassetti** [comment]
When I look at it before the image was broken, so I did not realize it was there. Sorry about that
