### ISSUE TITLE
Use mockito-inline to circumvent kotlin's final policy

### ISSUE THREAD

**Issue by Tallic** [nhaarman/mockito-kotlin#187]
To momentarily incubating inline mock macker allows the mocking of final classes enabling a better usage within kotlin.
Only change would be

`compile group: 'org.mockito', name: 'mockito-inline', version: version_mockito`

which is the same version as the core except the spi enabled extension.

**Comment by nhaarman** [comment]
Since the feature is incubating, this library does not include it by default. It is easy enough to use it alongside the Mockito-Kotlin library.

**Comment by Tallic** [comment]
Fair enough
