### ISSUE TITLE
[Feature Request] - any() vs any<?>()

### ISSUE THREAD

**Issue by jaredsburrows** [nhaarman/mockito-kotlin#189]
According to this article: https://medium.com/@elye.project/befriending-kotlin-and-mockito-1c2e7b0ef791

```
private fun <T> any(): T {
    Mockito.any<T>()
    return uninitialized()
}
private fun <T> uninitialized(): T = null as T
```
Allows us to use it like this `any<Object>()` in our tests.

Here is what you have in your current library:
```
inline fun <reified T : Any> any() = Mockito.any(T::class.java) ?: createInstance<T>()
```
https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/Mockito.kt#L44

This does not work the same for me, as I still receive Mockito errors. Would you accept a PR including the the "any" version from the article?

**Comment by nhaarman** [comment]
`createInstance<T>()` eventually uses this same exact code:

[NullCaster.kt](https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/src/main/kotlin/com/nhaarman/mockito_kotlin/createinstance/NullCaster.kt):

```kotlin
internal class NullCaster : NonNullProvider {

    override fun <T : Any> createInstance(kClass: KClass<T>): T {
        return castNull()
    }

    private fun <T> castNull(): T = null as T
}
```
