### ISSUE TITLE
Cannot throw exception

### ISSUE THREAD

**Issue by dinomite** [nhaarman/mockito-kotlin#192]
I have a method that throws a custom exception

```kotlin
class SiteRuleService {
    fun extractDomain(uri: URI): String {
        throw InvalidUrlException("Invalid URL or domain <${uri.toASCIIString()}>")
    }
}

class InvalidUrlException(override val message: String = "") : Exception(message)
```

And a test to exercise this method:

```kotlin
@Test
fun testFindPagechat_InvalidUrlForBadUrl() {
    val inputUri = URI("http://example.com")
    doThrow(InvalidUrlException("Invalid URL or domain"))
            .whenever(siteRuleService).extractDomain(inputUri)

    try {
        siteRuleService.extractDomain(inputUri)
        fail("Expected exception")
    } catch (e: InvalidUrlException) {
        assertEquals("Invalid URL or domain", e.message)
    }
}
```

But Mockito complains because the method doesnt' declare `IUE` as a checked exception (since we can't in Kotlin):

```
org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: net.forumforall.kuorum.pagechat.InvalidUrlException: Invalid URL or domain
```

Any way around this?

**Comment by sauloaguiar** [comment]
Just ran into the same issue. I noticed that Kotlin doesn't have checked exceptions, but I'm not sure how this would relate to the issue

**Comment by nhaarman** [comment]
Kotlin has the `@Throws` annotation which you can use:

```
@Throws(InvalidUrlException::class)
fun extractDomain(uri: URI): String {
  throw InvalidUrlException("Invalid URL or domain <${uri.toASCIIString()}>")
}
```

**Comment by dinomite** [comment]
Thanks, @nhaarman, that gets exactly what I needed, easy fix!

**Comment by james-ralston** [comment]
Is it a good idea to add annotations to source code just for testing purposes? I understand writing testable code and writing in a way that makes it testable, but this seems like a stretch and introduces something excluded from the language

**Comment by nhaarman** [comment]
This is not just for testing purposes, but for general interoperability with Java. See https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#checked-exceptions

**Comment by james-ralston** [comment]
I understand the interop reason for the annotation, but more generally there may be no reason for it in the application code, but just testing code. I have a particular use case with no Java code, but am running into this issue. I would rather have the ability to maneuver in the testing framework than change source code.

**Comment by zakyvr** [comment]
However if Java interop is not required in a project, these annotations become needed solely to get the testing framework working. This adds unnecessary noise to the production code.

**Comment by jibidus** [comment]
Here is a workaround :
```
doAnswer { throw InvalidUrlException("Invalid URL or domain") }
            .whenever(siteRuleService)
            .extractDomain(inputUri)
```

**Comment by Damien-L** [comment]
Thanks @jibidus for the workaround because, to my knowledge, there is no other solution when you want to do it on a @Transaction method on an Android Room DAO.

**Comment by FrancisBaileyH** [comment]
This can also be achieved by doing:

```
whenever(someObject.doesSomething(any()).then {
    throw MyCheckedException("Error")
}
```
