### ISSUE TITLE
Proper way to declare nested mocks (i.e in lists)

### ISSUE THREAD

**Issue by Kinmarui** [nhaarman/mockito-kotlin#194]
Often happens that it would be nice to be able to define mocks containing lists of other mocks i.e

`mock<Parent>{ on { this.childList } doReturn listOf(mock<Child> { on { this.id } doReturn 1}) }`

**Comment by nhaarman** [comment]
That is not possible by Mockito design. The first `doReturn` needs to be completed before another one can be started.

**Comment by Kinmarui** [comment]
Ok :<
Do you have any recommendation how to deal with that type of situations? When it comes to nested object I can use deep stubs but that isn't possible with lists :/
