### ISSUE TITLE
Mockito Kotlin eats the NPE and converts it into something mysterious

### ISSUE THREAD

**Issue by tasomaniac** [nhaarman/mockito-kotlin#195]
Here is the code piece from the project 

```
fun <R> on(methodCall: T.() -> R): OngoingStubbing<R> {
        return try {
            Mockito.`when`(mock.methodCall())
        } catch(e: NullPointerException) {
            throw MockitoKotlinException("NullPointerException thrown when stubbing. If you are trying to stub a generic method, try `onGeneric` instead.", e)
        }
    }
```

Here, I understand what the code tries to achieve.

I had NPE in `methodCall` function and it was eaten and converted into this error message I don't understand at all. And it is also not related.

So I think, the project should not catch exceptions happening in `methodCall` function.

**Comment by nhaarman** [comment]
What is 'this error message'? Include the stack trace.

**Comment by nhaarman** [comment]
The original NPE is still shown in the stack trace, which should show up as 'caused by'. By wrapping the NPE the library tries to guide you into finding the issue. If the message is not applicable (you're not trying to stub a generic method), the natural thing to do is to find out why the NPE _did_ happen.

**Comment by tasomaniac** [comment]
Yes, that's what I did at the end. But initially I tried to understand what this message mean. I really didn't understand that and googled it of course. Then I only found the source code :) 

Anyways, if you think you cannot avoid catching NPE here, maybe you can modify the statement to say that the user might have NPE in their fun. Not just about generics etc.
