### ISSUE TITLE
Any intention to upgrade it to use Mockito2 and use newest kotlin version?

### ISSUE THREAD

**Issue by dibog** [nhaarman/mockito-kotlin#201]
Hello all,

I like this project very much. It makes working with Mockito much easier.

I have two questions:
* Is it planned that Mockito2 is used instead of Mocktio1?
* Could we release a new pom every time a major new Kotlin version is released?
  That would make it easier to use it in the maven world.

Best regards,
Dieter

**Comment by nhaarman** [comment]
Mockito-Kotlin [already depends on Mockito 2.8.9](https://github.com/nhaarman/mockito-kotlin/blob/master/mockito-kotlin/build.gradle#L29).

As for the Kotlin version conflicts, does explicitly depending on `kotlin-reflect:$kotlinVersion` for your test configuration solve the issue? I want to avoid adding multiple artifacts just based on Kotlin versions alone. In fact, I intend to deprecate `mockito-kotlin-kt1.1` in favor of adding the reflect dependency manually.

**Comment by dibog** [comment]
Ah, sorry, another maven dependency (spring-boot-test-starters) pulled the old mockito and with mvn dependency:tree it looked like mockito-kotlin would have done it.  So all is fine. :-)
