### ISSUE TITLE
Coroutine/suspend function mocking support

### ISSUE THREAD

**Issue by dave08** [nhaarman/mockito-kotlin#205]
If you use non-inline lambdas that are not declared as suspend, the runBlocking { } around the test function doesn't help, rather we need to `mock { on { runBlocking { suspendFun() } } }` for each mock...

**Comment by nhaarman** [comment]
Could you post a more elaborate example?

**Comment by dave08** [comment]
```kotlin
interface AccountRepository {
    suspend fun getAccountId(deviceNo: String): Int
}

class SUT(val repo: AccountRepository) {
   fun something() {
        launch(CommonPool) { println(repo.getAccountId("0000")) }
  }
}

// Test function
val repoMock:AccountRepo = mock { onGeneric { runBlocking { getAccountId(any()) } } doReturn 3300 }

val sut = SUT(repoMock)
sut.something()

// Do some assertions on mock
```

**Comment by dave08** [comment]
If the mock and onGeneric lambdas were either suspend functions or inline, then I wouldn't need to put runBlocking inside the onGeneric for every function, I could just surround the whole mock {} with runBlocking, it would be much cleaner.

**Comment by 540Grunkspin** [comment]
Isn't this gonna be sort of hard to implement if you want to have the library compatible with pre 1.1 kotlin? Maybe soon Gradle magic?

**Comment by 540Grunkspin** [comment]
Or maybe it's enough to just make them inline.

**Comment by dave08** [comment]
It might be enough to make them into extension functions that are inline,
I'm just not sure about nested dsl working that way...

בתאריך 2 באוק׳ 2017 7:55 PM,‏ "540Grunkspin" <notifications@github.com> כתב:

**Comment by 540Grunkspin** [comment]
I created a pull request for a suggested fix. Seems like all the previous tests are passing but still waiting for the CI to run.

Not sure if this is exactly what you wanted. There is an example test in there as well.

**Comment by dave08** [comment]
Thanks, I'm on vacation for a week, but when I get back I'll try it out!
I'm sure it'll help lots of people, if coroutines pick up as much as Kotlin
did...

בתאריך 3 באוק׳ 2017 6:46 PM,‏ "540Grunkspin" <notifications@github.com> כתב:

**Comment by PaulWoitaschek** [comment]
Any news on this? It's the same with `given`

```
    given { runBlocking { mockLoginManager.refreshToken() } }
        .willReturn {
          TokenFactory.create(expired = false)
        }
```

Creates quite some noise whenever there is a suspending function.

**Comment by 540Grunkspin** [comment]
I tried to switch to inline but that didn't really fix the problem, not sure if I'm smart or knowledgeable enough to fix it. Feel free to pick up where I left off. See my linked pull request.

**Comment by nhaarman** [comment]
I don't really use coroutines much myself. I can suggest this solution:

```kotlin
fun <T : Any, R> KStubbing<T>.onBlocking(
      m: suspend T.() -> R
): OngoingStubbing<R> {
    return runBlocking { Mockito.`when`(mock.m()) }
}
```
.. but I don't know if it covers all scenarios. The following test passes:

```
interface SomeInterface {

    suspend fun foo(): Int
}

@Test
fun test() = runBlocking {
    val m = mock<SomeInterface> {
        onBlocking { foo() } doReturn 42
    }

    val result = m.foo()

    expect(result).toBe(42)
}
```

**Comment by bohsen** [comment]
The above solution works.

**Comment by nhaarman** [comment]
Awesome, thanks! I'll look into this soon.

**Comment by Aetherna** [comment]
Can not access mock in mock.m() <- it is private in KStubbing.
What to do?

**Comment by ZakTaccardi** [comment]
what if I want to control *when* the suspending function returns? is this possible?

**Comment by carterhudson** [comment]
"mock" is private in KStubbing...

**Comment by juanchosaravia** [comment]
Pointing to this version I was able to use directly the onBlocking function:
"com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0-alpha04"

I tried using latest version:
"com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0-RC1"
but onBlocking is not available anymore and I don't know if there is another function that is replacing this.

**Comment by mochadwi** [comment]
`expect(m).toBe(42)` I cannot find this method signature in your library @nhaarman , is this an assertion/verify mocking?

**Comment by nhaarman** [comment]
> > .. but I don't know if it covers all scenarios. The following test passes:
> > 
> > ```
> > interface SomeInterface {
> > 
> >     suspend fun foo(): Int
> > }
> > 
> > @Test
> > fun test() = runBlocking {
> >     val m = mock<SomeInterface> {
> >         onBlocking { foo() } doReturn 42
> >     }
> > 
> >     val result = m.foo()
> > 
> >     expect(result).toBe(42)
> > }
> > ```
> 
> I cannot find this method signature in your library @nhaarman , is this an assertion/verify mocking?
> 
> 

See github.com/nhaarman/expect.kt

**Comment by mochadwi** [comment]
Nice thanks a lot @nhaarman

**Comment by MedetZhakupov** [comment]
> I don't really use coroutines much myself. I can suggest this solution:
> 
> ```kotlin
> fun <T : Any, R> KStubbing<T>.onBlocking(
>       m: suspend T.() -> R
> ): OngoingStubbing<R> {
>     return runBlocking { Mockito.`when`(mock.m()) }
> }
> ```
> 
> .. but I don't know if it covers all scenarios. The following test passes:
> 
> ```
> interface SomeInterface {
> 
>     suspend fun foo(): Int
> }
> 
> @Test
> fun test() = runBlocking {
>     val m = mock<SomeInterface> {
>         onBlocking { foo() } doReturn 42
>     }
> 
>     val result = m.foo()
> 
>     expect(result).toBe(42)
> }
> ```

While this might work fine for interface's suspend function it's not working for me in mocking below suspend function type 
`someFunction: suspend (): Boolean`. Throws `NullPointerException`. If I remove suspend keyword and use simple mocking like `on { invoke() }.doReturn { true }` it also throws `NullPointerException` but when I change it to  `onGeneric { invoke() }.doReturn { true }` then it works fine. In suspend case I am not sure what might be the alternative for that. Anyone has any clue how I can approach this?
