### ISSUE TITLE
Cannot verify if method of mocked object is called with correct argument

### ISSUE THREAD

**Issue by fernandospr** [nhaarman/mockito-kotlin#207]
How to reproduce:

```
class KotlinTests {

    open class Repository {
        fun getItems(query: String) {
        }
    }

    class Presenter(val repository: Repository) {
        fun show(query: String) {
            repository.getItems(query)
        }
    }

    @Test
    fun test() {
        val repository:Repository = mock()
        val presenter = Presenter(repository)
        presenter.show("test")
        verify(repository).getItems(argWhere<String> { it == "test"})
    }
}
```

Running this test would return:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.mycompany.KotlinTests$Repository.getItems, parameter query
```

I have also tried doing this:
```verify(repository).getItems("test")```
and the test passes but also the following passes (but should not):
```verify(repository).getItems("another string")```

I have also tried doing this:
```verify(repository).getItems(eq("test"))```
and the test passes but also the following passes (but should not):
```verify(repository).getItems(eq("another string"))```

**Comment by fernandospr** [comment]
I have also tried this, it is not working:

```
    @Test
    fun test2() {
        val repository = mock<Repository>()
        val presenter = Presenter(repository)

        argumentCaptor<String>().apply {
            verify(repository).getItems(capture())
            Assert.assertEquals("test", firstValue)
        }

        presenter.show("test")
    }
```

It is throwing: ```java.lang.IndexOutOfBoundsException: Index: 0, Size: 0```

**Comment by fernandospr** [comment]
I'm answering to myself here.
After reading a lot, I understood that Kotlin, by default, has final classes and final methods, unless the `open` keyword is specified.
Mockito cannot spy/mock final classes. 
Mockito cannot spy/mock final methods, it will call the real method.

To overcome this, one can use `open ClassName` and `open fun`, so the following tests now pass:
```
class KotlinTests {

  open class Repository {
    open fun getItems(query: String) {
    }
  }

  class Presenter(val repository: Repository) {
    fun show(query: String) {
      repository.getItems(query)
    }
  }

  @Test
  fun test1() {
    val repository:Repository = mock()
    val presenter = Presenter(repository)
    presenter.show("test")
    verify(repository).getItems(argWhere<String> { it == "test"})
  }

  @Test
  fun test2() {
    val repository = mock<Repository>()
    val presenter = Presenter(repository)

    presenter.show("test")

    argumentCaptor<String>().apply {
      verify(repository).getItems(capture())
      Assert.assertEquals("test", firstValue)
    }
  }

  @Test
  fun test3() {
    val repository = mock<Repository>()
    val presenter = Presenter(repository)

    presenter.show("test")

    verify(repository).getItems(eq("test"))
  }
}
```

**Comment by arg20** [comment]
Mockito should be able to mock final classes ([see here](https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2))

if you create a file in `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` and add a single line in it: 

`mock-maker-inline`

**Comment by fernandospr** [comment]
Thank you! Yes, I’ve used it too. However, bear in mind that it’s still an incubating feature.
