### ISSUE TITLE
Update to 1.0.0 ?

### ISSUE THREAD

**Issue by fabiocarballo** [nhaarman/mockito-kotlin#21]
When do you release something with 1.0.0 ? Not the beta..

Thanks!

**Comment by nhaarman** [comment]
A 1.0.0 release generally means that the library works as it should, and that the risk of some major undiscovered problem is small. Discovering these problems takes time, so it might just be a while before that happens.

I'm not saying the library is buggy though, it just _might_ be :) There is a test suite that covers most of the basic functionality, so for day-to-day usage, you'll probably be fine.
