### ISSUE TITLE
Can't have mock return self

### ISSUE THREAD

**Issue by ScottPierce** [nhaarman/mockito-kotlin#210]
Inside of the mock running context, I'm trying to mock an Android `Application` object and have the mock return itself. I'd expect to be able to do something like this:
```Kotlin
on { applicationContext } doAnswer Mockito.RETURNS_SELF
```

Is there some way provided to accomplish this, or would this be an improvement?

**Comment by ScottPierce** [comment]
```Kotlin
on { applicationContext } doAnswer Mockito.RETURNS_SELF as (InvocationOnMock) -> Context?
```

The above seems to work, but it'd be nice if there was a better way.

**Comment by nhaarman** [comment]
The lambda of the `mock` method gets the `mock` instance as a parameter. So you should be able to do this:

```kotlin
mock<MyObject> { mock ->
  on { doSomething } doReturn mock
}
```

**Comment by ScottPierce** [comment]
Ah, perfect. Thanks for the recommendation. In this case, I think you are right, that works well.

Is there a better solution for me using:
```Kotlin
Mockito.RETURNS_DEFAULTS
Mockito.CALLS_REAL_METHODS
Mockito.RETURNS_SMART_NULLS
etc.
```

It might be nice if the `MockitoKotlin` class had some properties or functions that made these easier to use, or if `KStubbing` provided an easier way.

By the way, this library is extremely valuable to the Kotlin community. Thank you for maintaining it.
