### ISSUE TITLE
no doAnswer with an actual Answer parameter

### ISSUE THREAD

**Issue by speekha** [nhaarman/mockito-kotlin#212]
Why does the doAnswer infix function take an "InvocationOnMock" but not an "Answer" as a parameter? I wish I could replace my thenAnswer(Answer) with an infix doAnswer(Answer)...

**Comment by speekha** [comment]
Tried to create a pull-request, but I'm not allowed to push my branch. How could I do that?

**Comment by alexashley** [comment]
@speekha You'll have to [fork](https://help.github.com/articles/fork-a-repo/) this repository, [change your git remote](https://help.github.com/articles/changing-a-remote-s-url/) (`git remote set-url origin "myfork"`) and push to that. Then you should be able to make a pull request.
