### ISSUE TITLE
Missing doNothing() method

### ISSUE THREAD

**Issue by vojtapol** [nhaarman/mockito-kotlin#225]
I think we should be able to do:

```
whenever(mock.voidMethod()).thenDoNothing()
```

I know this is the default behavior for void methods, but this can be used to override previously defined `then { }` block.

**Comment by davidtcdeveloper** [comment]
I agree with that. Took me some time to understand that I should use `then { }`.

**Comment by nsmolenskii** [comment]
This method will be quite useful to operate with spy’s in order to prevent real method call.

**Comment by nhaarman** [comment]
There is a `doNothing()` function which you place in front of the invocation (like in plain Mockito):

```
    @Test
    fun testDoNothing() {
        val spy = spy(Open())
        val array = intArrayOf(3)

        doNothing().whenever(spy).modifiesContents(array)
        spy.modifiesContents(array)

        expect(array[0]).toBe(3)
    }
```

See https://github.com/nhaarman/mockito-kotlin/blob/94f17fa8655a672ef00547dc705f6a49c0a992e9/mockito-kotlin/src/test/kotlin/test/MockitoTest.kt#L290

**Comment by gkylafas** [comment]
How about using `doAnswer {}` as in
```kotlin
val spy = spy(object) {
    on { methodCall() } doAnswer {}
}
```
?

**Comment by avisecag** [comment]
Concerning doNothing().whenever ... , it doesn't seem to be present in mockitokotlin2. What is the replacement? I couldn't find anything obvious.

**Comment by vojtapol** [comment]
> Concerning doNothing().whenever ... , it doesn't seem to be present in mockitokotlin2. What is the replacement? I couldn't find anything obvious.

The replacement is https://mockk.io/

**Comment by SImrul** [comment]
`donothing.whenever(mock.somefunction())` is not working in `com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0`. Same question as above, what is the replacement?

**Comment by yangzii0920** [comment]
any update?

**Comment by bh4r4th** [comment]
This worked for me:

```
doNothing().`when`(myMockedClass).someMethodStaticMethodFromMyMockedClass()
```
