### ISSUE TITLE
Cannot mock with Kotlin 1.2.10

### ISSUE THREAD

**Issue by fbiville** [nhaarman/mockito-kotlin#227]
Here is a simple class:

```
class TravisYamlClient(val gson: Gson) { [...] }
```
And the following mock call:

```
val travisYamlClient = mock<TravisYamlClient>()
```

Using this library (version 1.5.0) and Kotlin 1.2.10, we end up with the following error:

```
org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class org.liquigraph.sentinel.TravisYamlClient
Mockito cannot mock/spy following:
  - final classes
  - anonymous classes
  - primitive types
```

Does this library support Kotlin 1.2?

**Comment by bohsen** [comment]
I'm using it with kotlin 1.2.10 without any problems. Are you using the correct import of mock()?

**Comment by fbiville** [comment]
Yep, it's actually a PEBKAC.
I thought closed classes would be automagically open by the framework. 
Reading the FAQ made me realise it's not the case: https://github.com/nhaarman/mockito-kotlin/wiki/FAQ#q-will-this-library-help-mocking-closed-non-open-classes.
