### ISSUE TITLE
Consider updating build to use at least kotlin 1.1.0

### ISSUE THREAD

**Issue by bohsen** [nhaarman/mockito-kotlin#229]
This would add:
1. Support for suspending functions
2. Support for nullable types in argumentCaptor function (Maybe elsewhere too?)
`val captor = argumentCaptor<String?>()`

You could change ArgumentCaptor to this:

`inline fun <reified T : Any?> argumentCaptor(): KArgumentCaptor<T> = KArgumentCaptor(ArgumentCaptor.forClass(T::class.java), T::class)`

and maybe get rid of nullableArgumentcapture function, which is difficult to use unless you now how to do it.

**Comment by nhaarman** [comment]
This is indeed something I want to do. I still want to make sure Kotlin 1.0.7 is supported, so I'll have to think of some CI thingy to make that work.

**Comment by bohsen** [comment]
👍 I just noticed that version 2.0 mght be upcoming. That's always a good time to for som clean up.
