### ISSUE TITLE
Compatibility with PowerMock

### ISSUE THREAD

**Issue by elyashivlavi** [nhaarman/mockito-kotlin#232]
This issue was raised before (https://github.com/nhaarman/mockito-kotlin/issues/9), and few things changed since then.

Currently it's possible to use PowerMock with `kotlintest` and `mockito-kotlin` using this setting:

```
@RunWith(PowerMockRunner::class)
@PowerMockRunnerDelegate(KTestJUnitRunner::class)
@PrepareForTest(ContextCompat::class)
class TestSpec: BehaviorSpec() {
....
            PowerMockito.mockStatic(ContextCompat::class.java)
            Mockito.`when`(ContextCompat.checkSelfPermission(any(), any())).thenReturn(PackageManager.PERMISSION_GRANTED)
```

Currently PowerMock works well with mockito2, since version 2.10.0 of mockito, so I used the following gradlde dependencies:
```
dependencies {
    testImplementation "io.kotlintest:kotlintest:2.0.5"
    testImplementation "com.nhaarman:mockito-kotlin:1.5.0"
    testImplementation "org.mockito:mockito-core:2.13.0"
    testImplementation "org.powermock:powermock-api-mockito2:2.0.0-beta.5"
    testImplementation "org.powermock:powermock-module-junit4:2.0.0-beta.5"
}
```

Note that I still need to include `mockito-core:2.13.0` since powermock works good with mockito 2.10 and above, but the mockito in mockito-kotlin is 2.8.9.

Is it possible to upgrade mockito-kotlin to use the latest mockito?

**Comment by nhaarman** [comment]
This will come naturally in a new release. In the mean time, you can depend on the specific version yourself.
