### ISSUE TITLE
Roadmap for 2.0

### ISSUE THREAD

**Issue by guenhter** [nhaarman/mockito-kotlin#237]
HI,

what is the Roadmap for 2.x?
Really like your project and looking forward to any new features.

**Comment by nhaarman** [comment]
Version 2.0.0-alpha03 is now available, which includes support for coroutines. 
I don't expect much to change from this version on, but I want to be sure there are no breaking changes.

Please try it out! See [the release notes for 2.0.0-alpha01](https://github.com/nhaarman/mockito-kotlin/releases/tag/2.0.0-alpha01) for upgrade info.

**Comment by guenhter** [comment]
Thx

**Comment by mpost** [comment]
@nhaarman The alpha03 is not on jcenter. Is there a recommended way to consume the library?

https://repo.jfrog.org/artifactory/libs-release-bintray/com/nhaarman/mockitokotlin2/mockito-kotlin/

**Comment by nhaarman** [comment]
Hmm, that's weird. Something must have gone wrong when publishing. I'll look into it!

**Comment by mpost** [comment]
Thanks. Looking forward to the mockito 2.13 upgrade.

**Comment by nhaarman** [comment]
It should be up now.
