### ISSUE TITLE
Using any<String>() with a spy throws IllegalArgumentException

### ISSUE THREAD

**Issue by dstarcev** [nhaarman/mockito-kotlin#241]
`any<String>()` returns null which works with mocks but fails with spies. A simple test to reproduce.
```
    @Test
    fun passAnyStringToSpy() {
        val my = spy(MyClass())
        whenever(my.foo(any())).thenReturn("mocked") // this throws java.lang.IllegalArgumentException: Parameter specified as non-null is null
        expect(my.foo("hello")).toBe("mocked") 
    }

    private interface MyInterface {
        fun foo(value: String): String
    }

    private open class MyClass : MyInterface {
        override fun foo(value: String) = value
    }
```

It seems that making `any<String>()` return `""` solves the problem, but one of the current tests fails:
`stubbingTwiceWithCheckArgumentMatchers_throwsException`

**Comment by nhaarman** [comment]
Due to `any()` returning `null` and the method `foo` being executed with it, the `IllegalArgumentException` is thrown. 

To prevent `null` from being passed to the actual code, you can use the alternative syntax as such:

```kotlin
    @Test
    fun passAnyStringToSpy() {
        /* Given */
        val my = spy(MyClass())

        /* When */
        doReturn("mocked").whenever(my).foo(any())

        /* Then */
        expect(my.foo("hello")).toBe("mocked")
    }

    private interface MyInterface {

        fun foo(value: String): String
    }

    private open class MyClass : MyInterface {

        override fun foo(value: String): String = value
    }
```

**Comment by dstarcev** [comment]
@nhaarman why does this work for mocks but fails with spies? Don't they both generate proxies, thus allowing nulls to be passed?

**Comment by nhaarman** [comment]
With `mock` you're not requesting to execute the real code as you're doing with `spy`. With your initial invocation (`whenever(my.foo(any()))`) Mockito doesn't know _not_ to execute `foo` yet (the `foo(any())` invocation happens before `whenever`), whereas with `doReturn("mocked").whenever(my).foo(any())` it does know this.

**Comment by dstarcev** [comment]
What if we implicitly skip the real code in spy in case of `any()` has been called before? Assuming this call to spy is for configuration.

**Comment by nhaarman** [comment]
That would be something the main Mockito library would have to pick up.

**Comment by jarrodmoldrich** [comment]
It would be nice to have this in the wiki.  I spent a few hours trying to figure out why the mock syntax didn't work for spies 😞   I could amend the wiki, and submit a PR if that helps, @nhaarman ?

**Comment by nkonev** [comment]
For me it helped to rewrite from `whenever(mock.aMethod(any())).doAnswer()`

onto

`doAnswer().whenever(mock).aMethod(any())`
