### ISSUE TITLE
Mockito doesn't play nice with Kotlin null-safety?

### ISSUE THREAD

**Issue by ahinchman1** [nhaarman/mockito-kotlin#249]
Can't seem to use Mockito properly passing objects in to a test without having the function for the class be designated "open".  It seems to be that when you initialize a `mock` object that contains a kotlin null-safe property, some weird proxying occurs where a function in the class to be tested will not be called without the class itself being open.  

Is there a particular reason why both sides of a function absolutely needs to be opened? I get that "passing an un-initialized object" will cause issues for dependency, but I'm wondering if anyone has considered the possibility of creating a mock function or simply creating a special Kotlin-version for Mockito functions anyObject()/any().  Null is technically polyamorous that can be assigned to any type, so maybe accepting an empty version of a type could be an alternative.

**Comment by nhaarman** [comment]
It's the Kotlin compiler that introduces `null` checks when a type is known to be non-nullable. Passing `any()` to a mock with a non-opened method will execute that method, and with that execute the generated `null` checks.

Is this what you mean? If not, could you provide a simple code example with what you're trying to do?
