### ISSUE TITLE
Can't test kotlin interface with default values

### ISSUE THREAD

**Issue by jt-gilkeson** [nhaarman/mockito-kotlin#251]
I have the following interface:
```
interface DataRepository {
    fun getData(id: String, type: String, page: Int = 1, perPage: Int = 20): Single<MyObject>
}
```

My real code that I want to test calls this interface with:
getData(id, type, page) 

In my test when I try to mock the the call:
`whenever(repository.getData(any(), any(), any())).thenReturn(Single.just(MyObject()))`
it complains
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
4 matchers expected, 3 recorded:
```

or
`whenever(repository.getData(any(), any(), any(), any())).thenReturn(Single.just(MyObject()))`
doesn't match the test call (returns null not MyObject())

anyOrNull() doesn't work since null is not allowed for the last 2 params

You can't apply JvmOverloads to an interface method.

So my question is how do I test this?

**Comment by bohsen** [comment]
Have you tried with `whenever(repository.getData(anyString(), anyString(), anyInt())).thenReturn(Single.just(MyObject()))`?

**Comment by jt-gilkeson** [comment]
Same Issue with repository.getData(anyString(), anyString(), anyInt())

org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
4 matchers expected, 3 recorded:

**Comment by jt-gilkeson** [comment]
Damn.  **My** mistake was with Rx not with Mokito.     The matcher for any(), any(), any(), any() or anyString(), anyString(), anyInt(), anyInt() works fine...  Sorry for the confusion!  Closing now.

**Comment by bkhablenko** [comment]
I stumbled upon this exact issue lately. If you're wondering why `any()` isn't working for you even though the comment above suggests it _should_ work, try using `anyOrNull()` instead.
