### ISSUE TITLE
Getting a null pointer exception when invoking a method on a mock

### ISSUE THREAD

**Issue by premnirmal** [nhaarman/mockito-kotlin#255]
I have a class:
``` kotlin
open class Foo(private val bar: Bar) {
  fun print(): String {
    return bar.print()
  }
}
```

When I mock this class in java, I get a null pointer exception.

``` java
Foo foo = Mockito.mock(Foo.class);
when(foo.print()).thenReturn("value"); // Null pointer exception saying bar is null.
```

``` java
Foo foo = Mockito.mock(Foo.class);
doReturn("value").when(foo).print(); // Null pointer exception saying bar is null.
```

``` java
Foo foo = Mockito.mock(Foo.class);
doReturn("value").when(foo.print()); // Null pointer exception saying bar is null.
```

With mockito-kotlin:

``` kotlin
foo = mock<Foo>()
whenever(foo.print()).thenReturn("value") // Null pointer exception saying bar is null.
```

How do you get around this?

**Comment by bohsen** [comment]
You should use doReturn/when construct instead of whenever/thenReturn.

An explanation can be found [here](https://stackoverflow.com/a/29394497/1495686).

**Comment by premnirmal** [comment]
@bohsen still getting the same issue when doReturn/when is used, updated the description with the different cases

**Comment by bohsen** [comment]
No problems here.

Minimal Working Example (MWE):

open class Foo(private val bar: Bar) {
        fun print(): String {
            return bar.print()
        }
    }

    class Bar {
        fun print(): String {
            return "helle"
        }
    }

    @Test
    fun test() {
        val foo = mock<Foo>()
        whenever(foo.print()).thenReturn("value")
        expect(foo.print()).toBe("hello")
    }

This passes in my IDE. Of course I don't know your full implementation

**Comment by premnirmal** [comment]
I get an NPE when I run the exact code on my IDE. Wondering if it is the version of mockito:
- Mockito: `2.13.0`
- Mockito-kotlin `2.0.0-alpha03`

**Comment by premnirmal** [comment]
Ok - figured it out - it is because the method is final.

the method needs to be marked `open` for this to work:

``` kotlin
open class Foo(private val bar: Bar) {
    **open** fun print(): String {
        return bar.print()
    }
}

class Bar {
    fun print(): String {
        return "helle"
    }
}

@Test
fun test() {
    val foo = mock<Foo>()
    whenever(foo.print()).thenReturn("value")
    expect(foo.print()).toBe("value")
}
```

**Comment by 80211android** [comment]
Marking the method open, makes it work! Thank you very much!

**Comment by Saauan** [comment]
Does anyone know why this behaviour happens when the method is not "open" ?

**Comment by MyckolaPetrychko** [comment]
I am facing the same issue, but this time I am implementing an interface method that uses another class's method which for some reason returns null. Has anyone faced the same issue?

**Comment by argenkiwi** [comment]
In my case I was trying to mock a property which was annotated with `@JvmField`. Removing the annotation, which wasn't needed in my case, did the trick.
