### ISSUE TITLE
Update Mockito for 1.x.x branch

### ISSUE THREAD

**Issue by Khoulaiz** [nhaarman/mockito-kotlin#256]
I had some problem with the argThat argument (IncompatibleClassChangeError) and had to do a fallback to use the ArgumentMatcher from Mockito using the 1.5.0 release.
Upgrading the underlying Mockito to 2.8.3 fixed these problems and I can now use the argThat argument matching from mockito-kotlin without any problems.
A maintenance upgrade for the 1.5.x would prolly help others as well.

**Comment by robstoll** [comment]
Could you update at least to 2.12.3, would fix a JDK10 issue: https://github.com/mockito/mockito/issues/1300
