### ISSUE TITLE
Publish mockito-kotlin to Maven Central

### ISSUE THREAD

**Issue by qualidafial** [nhaarman/mockito-kotlin#26]
Please consider publishing to Maven Central so that those of us using Maven can take advantage of this library.

**Comment by serssp** [comment]
```
   <dependency>
            <groupId>com.nhaarman</groupId>
            <artifactId>mockito-kotlin</artifactId>
            <version>0.4.0</version>
        </dependency>

 <repositories>
        <repository>
            <id>bintray-nhaarman-maven</id>
            <url>http://dl.bintray.com/nhaarman/maven</url>
        </repository>
    </repositories>
```

**Comment by nhaarman** [comment]
Indeed, you can use the above to use mockito-kotlin when using Maven.

**Comment by qualidafial** [comment]
This is your project and you can run it as you please, but I think you're hurting adoption by not taking the effort to put this on Maven Central. Dependency management is already a pain as it is; forcing folks to add a repository to adopt your project will make them look elsewhere. Moreover a project not hosted on Central tends to give folks a "fly-by-night" impression.

For what it's worth, this issue is the reason we didn't adopt your artifact.

If you change your mind, here is Maven's guide to getting stuff on Central: http://central.sonatype.org/pages/apache-maven.html

**Comment by nhaarman** [comment]
Ah, thanks. I didn't know that.
