### ISSUE TITLE
Matchers are not working for suspend functions

### ISSUE THREAD

**Issue by kostya-misura** [nhaarman/mockito-kotlin#269]
It seems that if you try to use  "matchers" (any, eq, etc.) on suspend function mockito fails with "InvalidUseOfMatchersException".

following test
```kotlin
@Test
fun otherTest() {
    val foo: Foo = mock {
        on { runBlocking { bar(any()) } } doReturn ("message")
    }
    Mockito.validateMockitoUsage()
}
```
with following interface definition
```kotlin
interface Foo {
    suspend fun bar(arg: String): String
}
```

produces following error
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:
-> at org.app.Tests$otherTest$i$1$1$1.doResume(Tests.kt:76)
```

**Comment by pablobaldez** [comment]
Do you have some news about this issue? There is an alternative approach to do?

**Comment by bohsen** [comment]
What version of mockito-kotlin are you using? Using version 2.0.0-RC your test should pass.

**Comment by kostya-misura** [comment]
I will check and get back to you on this one. Thanks!

**Comment by pablobaldez** [comment]
I think it's still not working. I change the dependencies to use the version  2.0.0-RC but the results are the same:
```kotlin
@Before
fun before() {
    runBlocking {
        `when`(jsFacade.portfolioExtractTabScreen(anyString(), anyOrNull(), anyBoolean()))
            .thenReturn(Resource.success(MorpheusContent()))
   }
}
```
when I tried to run the tests i'm getting:
```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
4 matchers expected, 3 recorded
```

**Comment by bohsen** [comment]
You want this setup before each test, then try this:

```
class TestClass {
    private val facadeMock = mock<JsFacade> {
         onBlocking { portfolioExtractTabScreen(anyString(), anyOrNull(), anyBoolean()) } doReturn Resource.success(MorpheusContent())
    }

    ... All the tests ...
}
```

Overwrite it in tests using 

```
...
@Test
fun myTest() = runBlocking {
    whenever(jsFacade.portfolioExtractTabScreen(anyString(), anyOrNull(), anyBoolean()))
            .thenReturn(Resource.failure(PortfolioException("Big mistake"))
   }
   ... Rest of the testcode ...
}
...
```

**Comment by pablobaldez** [comment]
Thank you for your reply.
I tried it and now i'm getting 
```
java.lang.NoClassDefFoundError: kotlinx/coroutines/experimental/BuildersKt
```
I'm using Kotlin 1.3 and in its version coroutines are not experimental. Do you have support for this kotlin version?

**Comment by nhaarman** [comment]
2.0.0-RC3 has just been released that supports non-experimental coroutines. Try again?

**Comment by pablobaldez** [comment]
now it's working perfectly. My tests are passing. Thank you

**Comment by ludddd** [comment]
One more failing test for this issue:
class MockTest {
    interface InterfaceA {
        suspend fun foo(i:Int)
    }

    @Test
    fun mock_test() = runBlocking{
        val mockObj = mock<InterfaceA>()
        mockObj.foo(10)
        verify(mockObj).foo(any())
    }
}

fails with:
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:

**Comment by bohsen** [comment]
@ludddd Are you using the correct imports? The example you provided passes ✅ when I try it.

@andrewborba10 You mock it like you would with mockito. Just use `whenever` and wrap the test with `runBlocking`. Modifying the example @ludddd provided:

```kotlin
class MockTest {
    interface InterfaceA {
        suspend fun foo(i:Int) : Int
    }

    @Test
    fun mock_test() {
        runBlocking{
            val mockObj = mock<InterfaceA>() // the mock in your case would be provided by dagger
            whenever(mockObj.foo(anyInt())).thenReturn(42)
            mockObj.foo(10)
            verify(mockObj).foo(any())
        }
    }
}
```

**Comment by bohsen** [comment]
This is with the same dependencies as you, only using mockito-core 2.23.0. But when downgrading to 2.15.0 the test still passes.

**Comment by ludddd** [comment]
Test passed when I set mockito-core to 2.23.0. But fails with 2.15.0.
Tried to switch mockito-core version to 2.15 in your code - test fails too.
And there is multiple test failures in CoroutineTest with it.
Seems that mockito-core 2.15 is the cause.

**Comment by andymoon** [comment]
I had to set my dependencies as below  in my gradle file for the matchers to work within a suspend. 
```
dependencies {
            testCompile 'com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0'
            testCompile("org.mockito:mockito-core:2.23.0")
}
```

**Comment by nhaarman** [comment]
Seems to have been resolved :+1:

**Comment by lborisevich-clgx** [comment]
@nhaarman looks like it's back

This produces the same error:

```
mock<suspend (Int) -> Int> {
    onBlocking { invoke(any()) } doReturn 1
}
```

I am using:
mockito-kotlin 2.2.0
mockito-core 3.6.28
kotlin 1.4.21

**Comment by xDPa** [comment]
same problem as @lborisevich-clgx . high order functions doesn't seem to work:

`typealias myFunction = suspend (Int) -> Boolean`

`org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:`

but works without parameter:

`typealias myFunction = suspend () -> Boolean`
