### ISSUE TITLE
kotlin anonymous callback can't capture

### ISSUE THREAD

**Issue by zhuruyi2013** [nhaarman/mockito-kotlin#276]
the declare of base callback is like this:
`typealias SucceedCallback<T> = ((t: T) -> Unit)`

now my capture code is:

argumentCaptor<SucceedCallback<ProfileFoundation?>>().apply {
            verify(apiService).getProfileInfo().subscribeRemoteData(capture())
            firstValue.invoke(foundation)
        }

then kotlin bytecode error:
Caused by: kotlin.KotlinNullPointerException

**Comment by nhaarman** [comment]
I'm not sure what you mean exactly. Could you include a MVCE with a full stack trace?

**Comment by nhaarman** [comment]
Closing due to inactiveness
