### ISSUE TITLE
Support mocking package-level functions?

### ISSUE THREAD

**Issue by XinyueZ** [nhaarman/mockito-kotlin#277]
```
fun foo(){...}

whenever(foo()).thenReturn(hello)
```

anyway?

**Comment by nhaarman** [comment]
That's an interesting question. I think from a higher-level point of view,  you wouldn't even want to mock such functions: they're supposed to be just utility functions. If they do bring logic you want to stub, it probably warrants it's own (mockable) class.

If you really want to do this, I guess your best bet is to raise an issue with the original Mockito library.

**Comment by nhaarman** [comment]
Mockito-Kotlin's aim is not to add deep functionality on top of Mockito core: having these kinds of things in one place is really the way to go.
I'm still standing by my original point, don't mock these functions.
