### ISSUE TITLE
mockito-kotlin with Kotlin 1.3

### ISSUE THREAD

**Issue by florina-muntenescu** [nhaarman/mockito-kotlin#286]
I know that mockito-kotlin uses now Kotlin 1.2.50. Any chance Kotlin 1.3 is going to be supported soon? 
I tried migrating a project to 1.3 M1 (see this [PR](https://github.com/nickbutcher/plaid/pull/502)) but then when I'm doing something like:
```
whenever(storiesRepository.loadStories(2)).thenReturn(result)
```
`storiesRepository.loadStories(2)` always returns `null`, instead of my `result`.

**Comment by nhaarman** [comment]
Definitely, though I'd like to wait until 1.3 becomes stable (I see a KotlinConf coming up :eyes:). 
'Just' updating the version to 1.3-RC currently breaks a lot of tests as well, with NPE's here and there.

I've created a separate issue for the coroutines issues (#294), and a PR that does the actual upgrade that fails (#295).

**Comment by nhaarman** [comment]
There is an issue in the Mockito-Core library that causes coroutine mocking to break when migrating away from the experimental feature. We will have to wait until Kotlin 1.3 is released and Mockito-Core merges https://github.com/mockito/mockito/pull/1501. 

Follow #294 and #295 for updates.
