### ISSUE TITLE
Introduce a `mock` delegate replacing mockito's @Mock annotation

### ISSUE THREAD

**Issue by damianogiusti** [nhaarman/mockito-kotlin#305]
A ReadOnlyProperty delegate `mock` will be useful for mocking test instance properties, which will be declared as `val` instead of `lateinit var`. 
This will remove the need to call `MockitoAnnotations.initMocks(this)` or the need to use the mockito rule.

Example syntax:
```kotlin
private val mockedInstance by mock<MockedClassType>()
```
instead of:
```kotlin
@Mock private lateinit var mockedInstance: MockedClassType
```

**Comment by nhaarman** [comment]
You could also just do 

```kotlin
private val mockedInstance = mock<MockedClassType>()
```

I don't think the delegation feature will add any value here?

**Comment by damianogiusti** [comment]
You're right. Maybe delegation can be useful for hiding how we retrieve that mocked instance, let's say for example if it's retrieved from a DI framework (i.e. the use case of DaggerMock). I was overthinking on an `inject` delegate. 
But for my actual purpose the simple instantiation will do the job. 
Thanks anyway! And thanks for providing the library!
