### ISSUE TITLE
How can we cover Lambdas

### ISSUE THREAD

**Issue by santoshgistto** [nhaarman/mockito-kotlin#321]
`alert.setPositiveButton(R.string.name) { _, _ ->
            (activity as? MyDialogListener)?.onDialog(editText?.text.toString())
        }`
How can we cover this ?

**Comment by bohsen** [comment]
Mock the lambda and `verify` that `invoke()` was called (of course using roboelectric to run it all).

```kotlin
@Test
fun mockLambda() {
    val mock = mock<() -> Unit>()
    val foo = Foo()
    foo.bar(mock)
    verify(mock).invoke()
}

class Foo {
    fun bar(lambda: () -> Unit) {
        lambda()
    }
}
```

**Comment by santoshgistto** [comment]
Thanks @bohsen 👍
