### ISSUE TITLE
not() matcher missed

### ISSUE THREAD

**Issue by sanekyy** [nhaarman/mockito-kotlin#326]
Hello.
Try to use your extention instead of base Mockito to fix matchers IllegalStateException in Kotlin.
Can't find replacement of mathcer "not()" which also returns null:(
My case is using combination: not(eq(myObject)).
Maybe I missed or don't understand something.
Thanks in advance for your reply.

**Comment by nhaarman** [comment]
`not` is part of the `AdditionalMatchers` class, for which none have been included in Mockito-Kotlin. Other than providing a unified namespace, there is no real benefit to have them in the library (i.e. there is nothing to 'Kotlinify' about them).
