### ISSUE TITLE
Unresolved reference: mock

### ISSUE THREAD

**Issue by givaldoms** [nhaarman/mockito-kotlin#331]
![image](https://user-images.githubusercontent.com/17015778/53655394-d28b0880-3c2e-11e9-9a30-bcc272436db5.png)

**Comment by krichter722** [comment]
Don't provide information as image which can be text. Don't raise an issue without description as it's unclear from just the image.

**Comment by nhaarman** [comment]
There is too little information to do anything with this question. It seems something is configured wrong, try to do a full clean build.
