### ISSUE TITLE
Mocking suspend function literal

### ISSUE THREAD

**Issue by pawegio** [nhaarman/mockito-kotlin#338]
I want to mock suspend function literal as follows:

```kotlin
val function = mock<suspend () -> Unit> {
    onBlocking { invoke() } doReturn Unit
}
```

Then verify suspending behavior:

```kotlin
verifyBlocking(function) { invoke() }
```

However, this verification fails. Is mocking suspend function literals already supported or I need to declare and mock an interface with suspend function as a member?

I'm using mockito-kotlin in version `2.0.0`.

**Comment by bohsen** [comment]
@pawegio 
```kotlin
val function = mock<suspend () -> Unit> {
    onBlocking { invoke() } doReturn Unit
}

@Test
fun verifySuspendLiteral() = runBlocking {
    function()
    verify(function).invoke()
}
```

or

```kotlin
@Test
fun verifySuspendLiteral() = runBlocking {
    val function = mock<suspend () -> Unit> {
        onBlocking { invoke() } doReturn Unit
    }
    function()
    verify(function).invoke()
}

**Comment by pawegio** [comment]
Thanks @bohsen 

It turned out to be an issue related to `CoroutineContext` in kotlintest framework. Anyway, I fixed it so I'm closing the issue since verification works fine.

**Comment by mkotyk** [comment]
I'm seeing an issue when the mocked suspend function has arguments.

```
  @Test
    fun verifySuspendLiteral() = runBlocking {
        val function = mock<suspend (Int) -> Unit> {
            onBlocking { invoke(any()) } doReturn Unit
        }
        function(5)
        verify(function).invoke(argForWhich { this == 5 })
    }
```

org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
2 matchers expected, 1 recorded:


com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0

**Comment by pawegio** [comment]
@mkotyk in `suspend fun` there is a hidden `Continuation` argument.

Declare an interface:
```kotlin
interface SuspendFunction<I, O> {
    suspend fun invokeSuspend(i: I): O
}
```

and in your case:
```kotlin
    @Test
    fun verifySuspendLiteral() = runBlocking {
        val function = mock<SuspendFunction<Int, Unit>> {
            onBlocking { invokeSuspend(any()) } doReturn Unit
        }
        function(5)
        verify(function).invokeSuspend(argForWhich { this == 5 })
    }
```
