### ISSUE TITLE
Who can contribute

### ISSUE THREAD

**Issue by nbentoneves** [nhaarman/mockito-kotlin#340]
I would like to know how can contributing to the project. :)

**Comment by krichter722** [comment]
The answer should be provided in the README. It makes to sense to leave a note whether the project maintainer(s) have a preference among feature code, test code, monetary or whichever support.

**Comment by nhaarman** [comment]
Hi, thanks for your interest! 

At the moment, the library has pretty much matured and there are no real 'features' that are being worked on. Changes in the library will most of the time be small bugfixes or modifications to keep up with the Mockito library.

If you think you've found a bug, or see a bug in the Issues list, see if you can tackle and fix it, and submit a pull request! Don't forget to test any code you've written though; for bugfixes I find it useful to write a test that fails before I do the bugfix, then actually do the bugfix and finally verify my test now succeeds.

I'll see if I can gather this up in some CONTRIBUTING document.
