### ISSUE TITLE
mock with suspend fun return null when not configured 

### ISSUE THREAD

**Issue by VinnieH** [nhaarman/mockito-kotlin#342]
I run into a bit problem in the following test:
```kotlin
interface TestClass {
  suspend fun doThingDelayed()
  fun doThing()
}

@Test
fun `problematic usage with not configured mock`() = runBlocking<Unit> {
  //setup
  val mock = mock<TestClass>()

  //act
  var value1 = mock.doThingDelayed()
  val value2 = mock.doThing()

  //assert
  verify(mock, times(1)).doThingDelayed()
  verify(mock, times(1)).doThing()
  println(value1)                    //This will print null
  println(value2)                    //This will print Unit
}
```
In the above case, both verify statement passed but `value1` is returned as null where it is suppsoed to Unit. 

For my partial use case that I running into the problem:
```Kotlin
fun myfunc(test : TestClass?) = runBlocking{
  test?.doThingDelayed()?:TODO("log failure")
}
```
running with default mock will pass verify AND execute TODO.

My current mitigation is actually configuring the mock and return Unit.
```kotlin
val mock = mock<TestClass> {
  onBlocking { doThingDelayed() } doReturn Unit
}
```
The question here is why `suspend fun` default behaves differently. It is a bit unexpected that the default value returned as null and I am having a hard time figuring out why. I try the same with just Mockito and it appears to have the same problematic behavior but I think it is good to place to ask here since we are focusing on Kotlin support. 

I have a bit suspension on the infered return type and I think mock treat them as Unit? and the default for that is null but I am not knowledgeable enough to verify that.

**Comment by bohsen** [comment]
@VinnieH This is because Mockito-core deals with kotlin suspending functions in a special way. Mockito-core doesn't recognize the suspend method as a void method. 
You will notice this if you add a breakpoint to `value1` and run the test in debug mode. It recognizes the method signature as:

`public abstract java.lang.Object test.CoroutinesTest$TestClass.doThingDelayed(kotlin.coroutines.Continuation)`

And Mockito will return null unless configured otherwise.

**Comment by nhaarman** [comment]
☝️ This is the correct answer. If this is behaviour you'd like to see changed, please file an issue in the Mockito core project.
