### ISSUE TITLE
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

### ISSUE THREAD

**Issue by snazhmudinov** [nhaarman/mockito-kotlin#344]
I'm trying a very simple test case, and getting the error. 

My gradle dependecy includes:
`androidTestImplementation 'com.nhaarman.mockitokotlin2:mockito-kotlin:2.1.0'`

This is my test class:

`@RunWith(AndroidJUnit4::class)
class ExampleInstrumentedTest {

    lateinit var viewModel: ViewModel
    lateinit var repository: Repository

    @Before
    fun setup() {
        repository = mock()
        viewModel = ViewModel(repository)
    }

    @Test
    fun sampleTest() {
        assert(true)
    }
}`

**Comment by snazhmudinov** [comment]
I also have MockMaker file configured and place under the `src/androidTest/resources/mockito-extension/org.mockito.plugins.MockMaker`

**Comment by nhaarman** [comment]
This is something core related. Could you file it with the Mockito core project?
