### ISSUE TITLE
eq and any failing with data classes

### ISSUE THREAD

**Issue by K0zka** [nhaarman/mockito-kotlin#35]
Looks like regardless of what data class eq and any has to instantiate, it always fails

```
java.lang.ClassCastException: org.mockito.Answers cannot be cast to org.mockito.stubbing.Answer

	at com.nhaarman.mockito_kotlin.CreateInstanceKt.uncheckedMock(CreateInstance.kt:162)
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.createNullableInstance(CreateInstance.kt:151)
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.newInstance(CreateInstance.kt:139)
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.createInstance(CreateInstance.kt:60)
```

Reproduces always with version 0.4.0

**Comment by nhaarman** [comment]
Can you provide your code as well? These two tests are passing at the moment:

    data class DataClass(val name:String)

    @Test
    fun eqDataClassInstance() {
        /* Given */
        val dataClassInstance = DataClass("")

        /* When */
        val result = eq(dataClassInstance)

        /* Then */
        expect(result).toNotBeNull()
    }

    @Test
    fun anyDataClassInstance() {
        /* When */
        val result = any<DataClass>()

        /* Then */
        expect(result).toNotBeNull()
    }

**Comment by sbuettner** [comment]
I got a similar error message when trying to use `any` with a generic interface like this:
 ```
whenever(someMethod(any<RowMapper<MyDataClass>>())).thenReturn(...)
```

Stacktrace: 
java.lang.ClassCastException: org.mockito.Answers cannot be cast to org.mockito.stubbing.Answer
at com.nhaarman.mockito_kotlin.CreateInstanceKt.uncheckedMock(CreateInstance.kt:178)
at com.nhaarman.mockito_kotlin.CreateInstanceKt.createInstance(CreateInstance.kt:58)
...
```

I currently use `Matchers.any<RowMapper<MyDataClass>>())` as a workaround.

**Comment by nhaarman** [comment]
Let's reopen this issue for further investigation.

**Comment by nhaarman** [comment]
If anyone could make a PR with a solid test that fails with this issue, we could try and tackle it.

**Comment by nhaarman** [comment]
It looks like this issue and #39 are caused by using Mockito 1.x. This library really focuses on the soon-to-be-released 2.x version.
