### ISSUE TITLE
doNothing() cannot be used on suspend Unit functions

### ISSUE THREAD

**Issue by Nimrodda** [nhaarman/mockito-kotlin#350]
Mocking Unit method where the first call should `doNothing()` and then 2nd `doThrow()`, produces the following error:

`Only void methods can doNothing()!`

Example:

`doNothing().doThrow(RuntimeException::class.java).whenever(mock).foo()` where `foo()` is `suspend fun foo()`.

**Comment by nhaarman** [comment]
`Mockito.doNothing()` and [its related `Stubber` functions](https://static.javadoc.io/org.mockito/mockito-core/2.28.2/org/mockito/Mockito.html#do_family_methods_stubs) are provided as a workaround for "[rare occasions when you cannot use `Mockito.when(Object)`](https://static.javadoc.io/org.mockito/mockito-core/2.28.2/org/mockito/Mockito.html#doReturn-java.lang.Object-)". One example is stubbing methods that return `Void`: the Java compiler doesn't allow `Void` inside brackets.

In this case, you're not returning `Void`, you're returning `Unit`, and you're better off returning to the non-workaround solutions: `whenever(mock.foo()).thenThrow(RuntimeException::class.java)` _is_ allowed.

**Comment by Nimrodda** [comment]
Oh yeah, I can't believe I missed that. Unit after all is just an object...
Thanks a lot! :)

**Comment by radityagumay** [comment]
i did something like this

```kotlin
when(foo.save("key", "value")).thenReturn(Unit)
```

**Comment by iadcialim** [comment]
@nhaarman In my case, when a **suspend** function of a mocked or spied object is called, I don't want it to do whatever it has inside. So its like **doNothing** but that now for functions that return a Unit. But now it does not work as specified above. Any workaround for this?

**Comment by radityagumay** [comment]
@iadcialim could you please share you gist?

**Comment by gkylafas** [comment]
@radityagumay I believe this is the problem that @iadcialim is facing:

```kotlin
class StubSuspendingTest {
    @Test
    fun `stubbing on suspending unit`() = runBlocking {
        val testSubject: SomeClass = spy(SomeClass()) // NOTE: spy vs mock

        whenever(testSubject.suspendingUnit()) // this calls the actual method impl
            .thenReturn(Unit)
            .thenThrow(RuntimeException("Foo"))

        assertEquals(Unit, testSubject.suspendingUnit())
        try {
            testSubject.suspendingUnit()
        } catch (error: Throwable) {
            assertEquals("Foo", error.message)
        }
    }
}

interface SomeInterface {
    suspend fun suspendingUnit(): Unit
}

class SomeClass : SomeInterface {
    override suspend fun suspendingUnit() {
        TODO("not implemented")
    }
}
```

**Comment by gkylafas** [comment]
@iadcialim You can use
```kotlin
doReturn(Unit).whenever(spy).functionReturningUnit()
```
 which does *not* execute `functionReturningUnit()` as 
```kotlin
whenever(spy.functionReturningUnit()).thenReturn(Unit)
```
would.
