### ISSUE TITLE
Call real default method implementation on a mock of interface

### ISSUE THREAD

**Issue by Adambl4** [nhaarman/mockito-kotlin#41]
```
interface MyInterface {
    fun bar()
    fun foo() {
      // optional body
    }
}

whenever(mock<MyInterface>().foo()).thenCallRealMethod()
```

It seems to me it's not possible until Kotlin would not support generating Java 8 byte code, isn't it?

**Comment by nhaarman** [comment]
The decompiled byte code looks like (without `bar()`):

```java
public interface MyInterface {
    void foo();

    public static final class DefaultImpls {
        public static void foo(MyInterface $this) {
            // optional body
        }
    }
}
```

`foo()` is still an abstract method on the interface, so you cannot call this method when mocking `MyInterface`. When creating a class that implements `MyInterface` and does not override `foo()` itself, `DefaultImpls.foo()` is called:

```java
public class MyClass implements MyInterface {

      public void foo() {
         MyInterface.DefaultImpls.foo(this);
      }
}
```

So as a workaround, you can create an empty abstract class that implements `MyInterface`, and mock that instead:

```kotlin
abstract class MyAbstractClass : MyInterface

@Test
fun test() {
    whenever(mock<MyAbstractClass>().foo()).thenCallRealMethod()
}
```
