### ISSUE TITLE
java.lang.AbstractMethodError: abstract method when just compile mockito-kotlin library in espresso instrumental test

### ISSUE THREAD

**Issue by elye** [nhaarman/mockito-kotlin#46]
Hi Haarman,

I found an issue, as per reported in
http://stackoverflow.com/questions/38136983/java-lang-abstractmethoderror-abstract-method-when-running-espresso-on-kotlin-w

You could get the code from
https://github.com/elye/kotlinespressomock

And then just add your "library" in the build.gradle

androidTestCompile ("com.nhaarman:mockito-kotlin:0.4.1") {
    exclude group: "org.jetbrains.kotlin", module: 'kotlin-stdlib'
}

And run the instrumental test, MainActivityTest. You'll see the error.

Then it will fail. Inform you, in case you found the issue and solution. Feel free to update the stackoverflow when some solution is found. Thanks!!

**Comment by IRus** [comment]
What version of Kotlin you using?

**Comment by elye** [comment]
Tried on both 1.0.2 and 1.0.1-2

**Comment by IRus** [comment]
Please try latest version of mockito-kotlin - 0.5.1

**Comment by elye** [comment]
Nope. Doesn't solve the problem.

**Comment by nhaarman** [comment]
This library really depends on the beta version 2 of Mockito. The release of 2.0 is planned [next month](https://github.com/mockito/mockito/milestones) and since this library hasn't reached 1.0 either I don't think support for 1.X will come in this repository.
