### ISSUE TITLE
Document Argument Captors in README

### ISSUE THREAD

**Issue by TTransmit** [nhaarman/mockito-kotlin#52]
It would be nice to have an example of the syntax for using Argument Captors in Mockito-Kotlin. I got caught out because I used `argumentCaptor.capture()` instead of `capture(argumentCaptor)`. 

Here is an example of what it could be. 

### Argument Captors

These overcome the issue that Mockito `ArgumentCaptor.capture()` returns null, which results in an `IllegalStateException` in Kotlin. 

**Kotlin**:
```kotlin
val argumentCaptor = argumentCaptor<String>()
myClass.doSomething()
verify(classToMock).sendString(capture(argumentCaptor))
```

I can raise this as a pull request if helpful. I would suggest adding it below the Argument Matchers section.

**Comment by nhaarman** [comment]
The more idiomatic way is even:

```
myClass.doSomething()
verify(classToMock).sendString(capture { s ->
    assertEquals("test", s)
})
```

I will add an example to the readme.
