### ISSUE TITLE
mocking function literals

### ISSUE THREAD

**Issue by K0zka** [nhaarman/mockito-kotlin#54]
Is there a way to mock function literals? any() does not accept it...

**Comment by nhaarman** [comment]
The following works:

```
interface A {
  fun test(f: (String) -> Int)
}

@Test
fun test() {
  val a = mock<A>()
  verify(a).test(any<(String) -> Int)>())

  val f = mock<(String) -> Int>()
}
```

**Comment by K0zka** [comment]
Looks good, but resulted in
'''
java.lang.ClassCastException: org.mockito.Answers cannot be cast to org.mockito.stubbing.Answer

	at com.nhaarman.mockito_kotlin.CreateInstanceKt.uncheckedMock(CreateInstance.kt:178)
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.createInstance(CreateInstance.kt:58)
'''
Maybe this is related to #35 I will try to isolate the problem

**Comment by nhaarman** [comment]
Does this still happen for you with the latest version?
The following test passes for me (added the call to `test { 1 }`):

```
    interface A {
        fun test(f: (String) -> Int)
    }

    @Test
    fun test() {
        val a = mock<A>()
        a.test { 1 }
        verify(a).test(any<(String) -> Int>())
        verify(a).test(any())
    }
```

**Comment by nhaarman** [comment]
Closing this for now. If this is still an issue, let me know.
