### ISSUE TITLE
any() doesn't seem to work with latest Mockito (2.0.94-beta)

### ISSUE THREAD

**Issue by unintelligible** [nhaarman/mockito-kotlin#57]
Mockito have recently refactored the MockUtils class to be a static utility class (with a private constructor):

https://github.com/mockito/mockito/commit/3fe3b62d2bc5ac60bb85c4bed8870f51109d167c#diff-321079f7242b016035f4577222dfe7a3R26

However, mockito-kotlin tries to instantiate an instance of it - see CreateInstance.kt line 180:

`    return MockUtil().createMock(creationSettings).apply...`

This causes the following runtime error when executing a test which calls the any() method:
```
java.lang.IllegalAccessError: tried to access method org.mockito.internal.util.MockUtil.<init>()V from class com.nhaarman.mockito_kotlin.CreateInstanceKt
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.uncheckedMock(CreateInstance.kt:180)
	at com.nhaarman.mockito_kotlin.CreateInstanceKt.createInstance(CreateInstance.kt:58)
```

The fix should just be to call the static method instead - `MockUtil.createMock(creationSettings).apply...`

**Comment by nhaarman** [comment]
Could you check against the `dev` branch? This issue should be fixed in #55.

**Comment by christophsturm** [comment]
are you going to publish the current dev branch soon?

**Comment by nhaarman** [comment]
[`0.6.0`](https://github.com/nhaarman/mockito-kotlin/pull/59) has been released.

**Comment by unintelligible** [comment]
Great news, thanks  very much
