### ISSUE TITLE
mocking properties/fields

### ISSUE THREAD

**Issue by chisou** [nhaarman/mockito-kotlin#61]
Unfortunately the following doesn't work:
```kotlin
open class ClassUnderTest ( val property:String )
val mock = mock<ClassUnderTest>()
whenever( mock.property ).thenReturn("value")
assert( mock.property == "value" )
```
because:
> when() requires an argument which has to be 'a method call on a mock'

I think I understand the root cause of this but it still would be extremely helpful. I think while accessing variables directly is often considered a code smell in Java it is quite common for Kotlin. 

Do you see any chance to be able to change that behaviour?

**Comment by nhaarman** [comment]
The `property` val needs to be `open` as well:
```kotlin
open class ClassUnderTest (open val property:String )
```

**Comment by rachitmishra** [comment]
I created a mock object. 

```open class MyClass {
     lateinit var myProperty
}```

Now when I do

```whenever(myObject.myProperty).thenReturn(someValue)```

I get the error lateinit property not initialised.

**Comment by rachitmishra** [comment]
Nope, Then I started using stubs for the above issue.

**Comment by theooos** [comment]
Cheers, I'll look into it. Thanks.
