### ISSUE TITLE
Stubbing with any() on nullable values don't work with nulls since 0.6.0

### ISSUE THREAD

**Issue by neworld** [nhaarman/mockito-kotlin#63]
I don't know, it a bug or feature. 

I have an interface:
```
interface Api {
  fun getFeed(page: Int, score: Int?):Observable<Feed>
}
```
Stubbing:
```
whenever(api.getFeed(any(), any()).thenReturn(empty())
```

If I call with null param: `api.getFeed(0, null)`, I got `null`. 
With not null works fine: `api.getFeed(0, 0)`. 

All pre `0.6.0` versions worked. 

If I stub with `whenever(api.getFeed(any(), isNull()).thenReturn(empty())` - works

**Comment by nhaarman** [comment]
This is an underlying change in Mockito itself. `any()` does not allow for null values anymore. 
See https://github.com/mockito/mockito/pull/510.

**Comment by neworld** [comment]
Thanks @nhaarman

**Comment by nhaarman** [comment]
There seems to be a slight nuance for this. I have opened #66.
