### ISSUE TITLE
Introduce anyOrNull / anything()

### ISSUE THREAD

**Issue by nhaarman** [nhaarman/mockito-kotlin#66]
Mockito contains the following methods:

```java
/** Matches <strong>anything</strong>, including nulls and varargs. */
public static <T> T any() 

/** Matches any object of given type, excluding nulls. */
public static <T> T any(Class<T> type)
```

In Mockito-Kotlin, there is just `any()`, which currently uses Mockito's `any(Class<T>)` and thus excluding nulls.
Introducing `anyOrNull()` to resolve to Mockito's `any()` can resolve issues like in #63.

An alternative would be to name this `anything()`, since it also includes `varargs`.
We should be wary of any confusion that may arise between using `any()` or `anything()` though.

**Comment by nhaarman** [comment]
Proposal:

```diff
-inline fun <reified T : Any> any() = Mockito.any(T::class.java) ?: createInstance<T>()

+/** Matches any object, excluding nulls. */
+inline fun <reified T : Any> any() = Mockito.any(T::class.java) ?: createInstance<T>()
+
+/** Matches anything, including nulls and varargs. */
+inline fun <reified T : Any> anything() = Mockito.any() ?: createInstance<T>()
```

**Comment by neworld** [comment]
Any news about this?

**Comment by nhaarman** [comment]
I'm not quite convinced on the naming of the methods yet. Without reading any documentation, the difference between `any()` or `anything()` is not clear. Using `anyOrNull()` instead of `anything()` does not cover its functionality, and `anyOrNullOrVarargs()` is way too long.

**Comment by neworld** [comment]
I guess `anything` is not the best name. 

IMHO, from Kotlin perspective  `Any` means `any not-null object`. However `Any?` means `any object or null`. So `anyOrNull()` don't look very bad.

**Comment by nhaarman** [comment]
Perhaps we can create `anyOrNull()` _and_ `anyVararg()`, which both essentially point to `Mockito.any()`.

So we have:

 - `any()` for any instance of some class
 - `anyOrNull()` for any instance or null
 - `anyVararg()` for any vararg instance of some class

The fact that `anyOrNull()` and `anyVararg()` are interchangeable should not matter I think.

**Comment by neworld** [comment]
That naming looks reasonable and nice. And yeah, better than `anything()`
