### ISSUE TITLE
only mock interfaces

### ISSUE THREAD

**Issue by danielgomezrico** [nhaarman/mockito-kotlin#8]
Why I cant mock non final classes?

It was working on java and now with kotlin it just run the code that should not run on the mocked instances.

I dont want to create an interface for every object, or should i?

**Comment by nhaarman** [comment]
Are you sure your class has the `open` modifier? Classes are `final` by default in Kotlin.

**Comment by danielgomezrico** [comment]
Yeah, I have them with open, otherwise mockito will crash saying that cant mock final classes.

**Comment by nhaarman** [comment]
Can you provide a small executable example?

**Comment by danielgomezrico** [comment]
Sure, check this one https://github.com/MakinGiants/todayhistory/tree/feature/move_to_kotlin

**Comment by nhaarman** [comment]
I don't have JDK 8 installed. Could you extract the relevant parts?

**Comment by danielgomezrico** [comment]
You are right, the thing is that functions are final by default too. Thanks :+1:

**Comment by nhaarman** [comment]
Good to hear the issue is resolved!
