### ISSUE TITLE
Compatibility with PowerMock

### ISSUE THREAD

**Issue by blob0815** [nhaarman/mockito-kotlin#9]
Hi,

this lib looks really nice, thanks for sharing. I have a problem with PowerMock though which I am using to make final classes mockable. I do not want to open up all classes I want to mock just for testing. 

Thing is powermock-api-mockito still uses Mockito 1.x which is not compatible with 2.x you are using. Is there a way to work around this (apart from forking your project and make it use Mockito 1.x)? Or is there a version of PowerMock wich is already using Mockito 2.x that I am just not able to find?

How do you treat final classes you want to mock?

**Comment by nhaarman** [comment]
I haven't used PowerMock before, I normally make a decision between making the class non-final or creating an interface for it. This library does not solve these problems, so perhaps the best thing to do is to indeed make it use 1.x.

**Comment by nomisRev** [comment]
This has not been solved has it? Has any1 found a solution, otherwise I might just make a v1.x variant.

**Comment by nhaarman** [comment]
There is no intention for this library to support 1.x indeed.

**Comment by nomisRev** [comment]
Okay, I'm going to start a 1.x variant then forked from yours :) If any1 is interessed you can find it on my Github.
