### ISSUE TITLE
Mocking function literals

### ISSUE THREAD

**Issue by odlp** [nhaarman/mockito-kotlin#94]
Hi @nhaarman,

I'm hitting a roadblock trying to use Mockito Kotlin to accept any function literal at per #54. The exception is:

```
org.mockito.exceptions.base.MockitoException: 
ClassCastException occurred while creating the mockito mock :
  class to mock : 'kotlin.jvm.functions.Function0', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@7852e922'
  created class : 'kotlin.jvm.functions.Function0$MockitoMock$1488133923', loaded by classloader : 'MultipleParentClassLoader{parents=[sun.misc.Launcher$AppClassLoader@7852e922, org.robolectric.internal.bytecode.InstrumentingClassLoader@1f28c152]}'
  proxy instance class : 'kotlin.jvm.functions.Function0$MockitoMock$1488133923', loaded by classloader : 'MultipleParentClassLoader{parents=[sun.misc.Launcher$AppClassLoader@7852e922, org.robolectric.internal.bytecode.InstrumentingClassLoader@1f28c152]}'
  instance creation by : ObjenesisInstantiator

You might experience classloading issues, please ask the mockito mailing-list.
```

This verification in question is trying to use the suggested syntax from the earlier issue:

```kotlin
verify(mockCart).setQuantity(product, 1, any<() -> Unit>())
```

This is using:
- 'org.mockito:mockito-core:1.10.19'
- 'com.nhaarman:mockito-kotlin:0.7.0'

I've tried disabling the class cache after having a search for that exception, but this doesn't help:

```kotlin
class MockitoConfiguration : DefaultMockitoConfiguration() {
    override fun enableClassCache(): Boolean {
        return false
    }
}
```

Please could you help me identify if this is an issue with Mockito Kotlin or Roboelectric?

Thanks,
Oli

**Comment by nhaarman** [comment]
Mockito-Kotlin really is intended to use the 2.x version of Mockito. Using it with Mockito 1.x may cause such exceptions.

**Comment by odlp** [comment]
Hi @nhaarman thanks for the tip. Tried Mockito upgrading to 2.x and this solved the issue when trying to mock an example class. 

Unfortunately when mocking the intended subject it still throws the same exception. This leads me to think the issue is in our codebase. Temporarily we're circumventing the issue with an `isNotNull()` argument matcher, rather than `any<() -> Unit>()`.

Thanks again for your assistance.

**Comment by nhaarman** [comment]
If you can provide a short, self contained and compilable example, perhaps we can rule out parties.
